### YamlMime:PowerShellCmdlet1
uid: Az.Security.Get-AzSecurityAutomation
name: Get-AzSecurityAutomation
module: Az.Security
isPreview: false
summary: |-
  Gets security automations
description: |-
  Gets security automations
parameters:
  cmdletParameters:
  - name: DefaultProfile
    type: <xref href="Microsoft.Azure.Commands.Common.Authentication.Abstractions.Core.IAzureContextContainer" data-throw-if-not-resolved="False" />
    description: |-
      The credentials, account, tenant, and subscription used for communication with Azure.
    aliases:
    - AzContext
    - AzureRmContext
    - AzureCredential
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: Name
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      Resource name.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: ResourceGroupLevelResource
      position: Named
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: ResourceGroupName
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      Resource group name.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: ResourceGroupScope
      position: Named
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    - name: ResourceGroupLevelResource
      position: Named
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: ResourceId
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      ID of the security resource that you want to invoke the command on.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: ResourceId
      position: Named
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: true
      valueFromRemainingArguments: false
    supportsWildcards: false
  commonParameters: |-
    This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable,
    -InformationAction, -InformationVariable, -OutBuffer, -OutVariable, -PipelineVariable,
    -ProgressAction, -Verbose, -WarningAction, and -WarningVariable. For more information, see
    [about_CommonParameters](https://go.microsoft.com/fwlink/?LinkID=113216).
syntaxes:
- syntax: |-
    ```Syntax
    Get-AzSecurityAutomation
        [-DefaultProfile <IAzureContextContainer>]
        [<CommonParameters>]
    ```
  parameterSetName: SubscriptionScope
  isDefault: true
- syntax: |-
    ```Syntax
    Get-AzSecurityAutomation
        -ResourceGroupName <String>
        [-DefaultProfile <IAzureContextContainer>]
        [<CommonParameters>]
    ```
  parameterSetName: ResourceGroupScope
  isDefault: false
- syntax: |-
    ```Syntax
    Get-AzSecurityAutomation
        -ResourceGroupName <String>
        -Name <String>
        [-DefaultProfile <IAzureContextContainer>]
        [<CommonParameters>]
    ```
  parameterSetName: ResourceGroupLevelResource
  isDefault: false
- syntax: |-
    ```Syntax
    Get-AzSecurityAutomation
        -ResourceId <String>
        [-DefaultProfile <IAzureContextContainer>]
        [<CommonParameters>]
    ```
  parameterSetName: ResourceId
  isDefault: false
inputs:
- name: <xref href="System.String" data-throw-if-not-resolved="False" />
outputs:
- name: <xref href="Microsoft.Azure.Commands.Security.Models.Automations.PSSecurityAutomation" data-throw-if-not-resolved="False" />
examples:
- title: Example 1
  description: |-
    ```powershell
    Get-AzSecurityAutomation
    ```

    Gets all security automations under the subscription
metadata:
  content_git_url: https://github.com/Azure/azure-powershell/blob/main/src/Security/Security/help/Get-AzSecurityAutomation.md
  document type: cmdlet
  external help file: Microsoft.Azure.PowerShell.Cmdlets.Security.dll-Help.xml
  HelpUri: https://learn.microsoft.com/powershell/module/az.security/get-azsecurityautomation
  Module Name: Az.Security
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/main/src/Security/Security/help/Get-AzSecurityAutomation.md
  PlatyPS schema version: 2024-05-01
