### YamlMime:PowerShellCmdlet1
uid: Az.Batch.New-AzBatchApplicationPackage
name: New-AzBatchApplicationPackage
module: Az.Batch
isPreview: false
summary: |-
  Creates an application package in a Batch account.
description: |-
  The **New-AzBatchApplicationPackage** cmdlet creates an application package in an Azure Batch account.
parameters:
  cmdletParameters:
  - name: AccountName
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      Specifies the name of the Batch account to which this cmdlet adds an application package.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: "0"
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: true
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: ActivateOnly
    type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
    description: |-
      Indicates that this cmdlet activates an application package that has already been uploaded.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: ActivateOnly
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: true
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: ApplicationName
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      Specifies the name of the application.
    aliases:
    - ApplicationId
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: "2"
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: true
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: ApplicationVersion
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      Specifies the version of the application.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: "3"
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: true
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: DefaultProfile
    type: <xref href="Microsoft.Azure.Commands.Common.Authentication.Abstractions.Core.IAzureContextContainer" data-throw-if-not-resolved="False" />
    description: |-
      The credentials, account, tenant, and subscription used for communication with azure.
    aliases:
    - AzContext
    - AzureRmContext
    - AzureCredential
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: FilePath
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      Specifies the file to be uploaded as the application package binary file.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: UploadAndActivate
      position: Named
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: true
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: Format
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      Specifies the format of the application package binary file.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: "4"
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: true
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: ResourceGroupName
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      Specifies the name of the resource group that contains the Batch account.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: "1"
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: true
      valueFromRemainingArguments: false
    supportsWildcards: false
  commonParameters: |-
    This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable,
    -InformationAction, -InformationVariable, -OutBuffer, -OutVariable, -PipelineVariable,
    -ProgressAction, -Verbose, -WarningAction, and -WarningVariable. For more information, see
    [about_CommonParameters](https://go.microsoft.com/fwlink/?LinkID=113216).
syntaxes:
- syntax: |-
    ```Syntax
    New-AzBatchApplicationPackage
        [-AccountName] <String>
        [-ResourceGroupName] <String>
        [-ApplicationName] <String>
        [-ApplicationVersion] <String>
        [-Format] <String>
        -FilePath <String>
        [-DefaultProfile <IAzureContextContainer>]
        [<CommonParameters>]
    ```
  parameterSetName: UploadAndActivate
  isDefault: true
- syntax: |-
    ```Syntax
    New-AzBatchApplicationPackage
        [-AccountName] <String>
        [-ResourceGroupName] <String>
        [-ApplicationName] <String>
        [-ApplicationVersion] <String>
        [-Format] <String>
        [-ActivateOnly]
        [-DefaultProfile <IAzureContextContainer>]
        [<CommonParameters>]
    ```
  parameterSetName: ActivateOnly
  isDefault: false
inputs:
- name: <xref href="System.String" data-throw-if-not-resolved="False" />
- name: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
outputs:
- name: <xref href="Microsoft.Azure.Commands.Batch.Models.PSApplicationPackage" data-throw-if-not-resolved="False" />
examples:
- title: 'Example 1: Install an application package into a Batch account'
  description: |-
    ```powershell
    New-AzBatchApplicationPackage -AccountName "ContosoBatch" -ResourceGroupName "ContosoBatchGroup" -ApplicationName "Litware" -ApplicationVersion "1.0" -FilePath "litware.1.0.zip" -Format "zip"
    ```

    This command creates and activates version 1.0 of the Litware application, and uploads the contents of litware.1.0.zip as the application package content.
links:
- text: Get-AzBatchApplication
  href: ./Get-AzBatchApplication.yml
- text: Get-AzBatchApplicationPackage
  href: ./Get-AzBatchApplicationPackage.yml
- text: New-AzBatchApplication
  href: ./New-AzBatchApplication.yml
- text: Remove-AzBatchApplication
  href: ./Remove-AzBatchApplication.yml
- text: Remove-AzBatchApplicationPackage
  href: ./Remove-AzBatchApplicationPackage.yml
- text: Set-AzBatchApplication
  href: ./Set-AzBatchApplication.yml
metadata:
  content_git_url: https://github.com/Azure/azure-powershell/blob/main/src/Batch/Batch/help/New-AzBatchApplicationPackage.md
  document type: cmdlet
  external help file: Microsoft.Azure.PowerShell.Cmdlets.Batch.dll-Help.xml
  HelpUri: https://learn.microsoft.com/powershell/module/az.batch/new-azbatchapplicationpackage
  Module Name: Az.Batch
  ms.assetid: D53DAEB6-DC4F-473C-A193-A1E2A65326D4
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/main/src/Batch/Batch/help/New-AzBatchApplicationPackage.md
  PlatyPS schema version: 2024-05-01
