### YamlMime:PowerShellCmdlet1
uid: Az.SpringCloud.Remove-AzSpringCloudAppDeployment
name: Remove-AzSpringCloudAppDeployment
module: Az.SpringCloud
isPreview: false
summary: |-
  Operation to delete a Deployment.
description: |-
  Operation to delete a Deployment.
parameters:
  cmdletParameters:
  - name: AppInputObject
    type: <xref href="Microsoft.Azure.PowerShell.Cmdlets.SpringCloud.Models.ISpringCloudIdentity" data-throw-if-not-resolved="False" />
    description: |-
      Identity Parameter
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: DeleteViaIdentityApp
      position: Named
      isRequired: true
      valueFromPipeline: true
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: AppName
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      The name of the App resource.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: Delete
      position: Named
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    - name: DeleteViaIdentitySpring
      position: Named
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: AsJob
    type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
    description: |-
      Run the command as a job
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: Confirm
    type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
    description: |-
      Prompts you for confirmation before running the cmdlet.
    aliases:
    - cf
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: DefaultProfile
    type: <xref href="System.Management.Automation.PSObject" data-throw-if-not-resolved="False" />
    description: |-
      The DefaultProfile parameter is not functional.
      Use the SubscriptionId parameter when available if executing the cmdlet against a different subscription.
    aliases:
    - AzureRMContext
    - AzureCredential
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: InputObject
    type: <xref href="Microsoft.Azure.PowerShell.Cmdlets.SpringCloud.Models.ISpringCloudIdentity" data-throw-if-not-resolved="False" />
    description: |-
      Identity Parameter
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: DeleteViaIdentity
      position: Named
      isRequired: true
      valueFromPipeline: true
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: Name
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      The name of the Deployment resource.
    aliases:
    - DeploymentName
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: Delete
      position: Named
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    - name: DeleteViaIdentitySpring
      position: Named
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    - name: DeleteViaIdentityApp
      position: Named
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: NoWait
    type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
    description: |-
      Run the command asynchronously
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: PassThru
    type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
    description: |-
      Returns true when the command succeeds
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: ResourceGroupName
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      The name of the resource group that contains the resource.
      You can obtain this value from the Azure Resource Manager API or the portal.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: Delete
      position: Named
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: ServiceName
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      The name of the Service resource.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: Delete
      position: Named
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: SpringInputObject
    type: <xref href="Microsoft.Azure.PowerShell.Cmdlets.SpringCloud.Models.ISpringCloudIdentity" data-throw-if-not-resolved="False" />
    description: |-
      Identity Parameter
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: DeleteViaIdentitySpring
      position: Named
      isRequired: true
      valueFromPipeline: true
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: SubscriptionId
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      Gets subscription ID which uniquely identify the Microsoft Azure subscription.
      The subscription ID forms part of the URI for every service call.
    defaultValue: (Get-AzContext).Subscription.Id
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: Delete
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: WhatIf
    type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
    description: |-
      Shows what would happen if the cmdlet runs.
      The cmdlet is not run.
    aliases:
    - wi
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  commonParameters: |-
    This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable,
    -InformationAction, -InformationVariable, -OutBuffer, -OutVariable, -PipelineVariable,
    -ProgressAction, -Verbose, -WarningAction, and -WarningVariable. For more information, see
    [about_CommonParameters](https://go.microsoft.com/fwlink/?LinkID=113216).
syntaxes:
- syntax: |-
    ```Syntax
    Remove-AzSpringCloudAppDeployment
        -AppName <String>
        -Name <String>
        -ResourceGroupName <String>
        -ServiceName <String>
        [-SubscriptionId <String>]
        [-DefaultProfile <PSObject>]
        [-AsJob]
        [-NoWait]
        [-PassThru]
        [-WhatIf]
        [-Confirm]
        [<CommonParameters>]
    ```
  parameterSetName: Delete
  isDefault: true
- syntax: |-
    ```Syntax
    Remove-AzSpringCloudAppDeployment
        -AppName <String>
        -Name <String>
        -SpringInputObject <ISpringCloudIdentity>
        [-DefaultProfile <PSObject>]
        [-AsJob]
        [-NoWait]
        [-PassThru]
        [-WhatIf]
        [-Confirm]
        [<CommonParameters>]
    ```
  parameterSetName: DeleteViaIdentitySpring
  isDefault: false
- syntax: |-
    ```Syntax
    Remove-AzSpringCloudAppDeployment
        -Name <String>
        -AppInputObject <ISpringCloudIdentity>
        [-DefaultProfile <PSObject>]
        [-AsJob]
        [-NoWait]
        [-PassThru]
        [-WhatIf]
        [-Confirm]
        [<CommonParameters>]
    ```
  parameterSetName: DeleteViaIdentityApp
  isDefault: false
- syntax: |-
    ```Syntax
    Remove-AzSpringCloudAppDeployment
        -InputObject <ISpringCloudIdentity>
        [-DefaultProfile <PSObject>]
        [-AsJob]
        [-NoWait]
        [-PassThru]
        [-WhatIf]
        [-Confirm]
        [<CommonParameters>]
    ```
  parameterSetName: DeleteViaIdentity
  isDefault: false
inputs:
- name: <xref href="Microsoft.Azure.PowerShell.Cmdlets.SpringCloud.Models.ISpringCloudIdentity" data-throw-if-not-resolved="False" />
outputs:
- name: <xref href="System.Boolean" data-throw-if-not-resolved="False" />
examples:
- title: 'Example 1: Remove Spring Cloud Deployment by name'
  description: |-
    ```powershell
    Remove-AzSpringCloudAppDeployment -ResourceGroupName spring-cloud-rg -ServiceName spring-cloud-service -AppName gateway -DeploymentName default
    ```

    Remove Spring Cloud Deployment by name.
- title: 'Example 2: Remove Spring Cloud Deployment by pipeline'
  description: |-
    ```powershell
    Get-AzSpringCloudAppDeployment -ResourceGroupName spring-cloud-rg -ServiceName spring-cloud-service -AppName gateway -DeploymentName default | Remove-AzSpringCloudAppDeployment
    ```

    Remove Spring Cloud Deployment by pipeline.
metadata:
  content_git_url: https://github.com/Azure/azure-powershell/blob/main/src/SpringCloud/SpringCloud/help/Remove-AzSpringCloudAppDeployment.md
  document type: cmdlet
  external help file: Az.SpringCloud-help.xml
  HelpUri: https://learn.microsoft.com/powershell/module/az.springcloud/remove-azspringcloudappdeployment
  Module Name: Az.SpringCloud
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/main/src/SpringCloud/SpringCloud/help/Remove-AzSpringCloudAppDeployment.md
  PlatyPS schema version: 2024-05-01
