### YamlMime:PowerShellCmdlet1
uid: Az.Resources.Get-AzResourceGroupDeploymentStack
name: Get-AzResourceGroupDeploymentStack
module: Az.Resources
isPreview: false
summary: |-
  Gets Resource Group scoped Deployment Stacks.
description: |-
  Retrieve a resource group scoped deployment stack.
parameters:
  cmdletParameters:
  - name: DefaultProfile
    type: <xref href="Microsoft.Azure.Commands.Common.Authentication.Abstractions.Core.IAzureContextContainer" data-throw-if-not-resolved="False" />
    description: |-
      The credentials, account, tenant, and subscription used for communication with Azure.
    aliases:
    - AzContext
    - AzureRmContext
    - AzureCredential
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: Name
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      The name of the DeploymentStack to get
    aliases:
    - StackName
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: GetByName
      position: "1"
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: true
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: Pre
    type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
    description: |-
      When set, indicates that the cmdlet should use pre-release API versions when automatically determining which version to use.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: ResourceGroupName
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      The id of the ResourceGroup where the DeploymentStack is deployed
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: ListByResourceGroupName
      position: "0"
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: true
      valueFromRemainingArguments: false
    - name: GetByName
      position: "0"
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: true
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: ResourceId
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      ResourceId of the DeploymentStack to get
    aliases:
    - Id
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: GetByResourceId
      position: Named
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: true
      valueFromRemainingArguments: false
    supportsWildcards: false
  commonParameters: |-
    This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable,
    -InformationAction, -InformationVariable, -OutBuffer, -OutVariable, -PipelineVariable,
    -ProgressAction, -Verbose, -WarningAction, and -WarningVariable. For more information, see
    [about_CommonParameters](https://go.microsoft.com/fwlink/?LinkID=113216).
syntaxes:
- syntax: |-
    ```Syntax
    Get-AzResourceGroupDeploymentStack
        [-ResourceGroupName] <String>
        [-Pre]
        [-DefaultProfile <IAzureContextContainer>]
        [<CommonParameters>]
    ```
  parameterSetName: ListByResourceGroupName
  isDefault: true
- syntax: |-
    ```Syntax
    Get-AzResourceGroupDeploymentStack
        -ResourceId <String>
        [-Pre]
        [-DefaultProfile <IAzureContextContainer>]
        [<CommonParameters>]
    ```
  parameterSetName: GetByResourceId
  isDefault: false
- syntax: |-
    ```Syntax
    Get-AzResourceGroupDeploymentStack
        [-ResourceGroupName] <String>
        [-Name] <String>
        [-Pre]
        [-DefaultProfile <IAzureContextContainer>]
        [<CommonParameters>]
    ```
  parameterSetName: GetByName
  isDefault: false
inputs:
- name: <xref href="System.String" data-throw-if-not-resolved="False" />
outputs:
- name: <xref href="Microsoft.Azure.Commands.ResourceManager.Cmdlets.SdkModels.PSDeploymentStack" data-throw-if-not-resolved="False" />
examples:
- title: 'Example 1: Retrieve a stack named MyRGStack from the resource group MyResourceGroup'
  description: |-
    ```powershell
    Get-AzResourceGroupDeploymentStack -ResourceGroupName MyResourceGroup -Name MyRGStack
    ```

    Get a deployment stack named 'MyRGStack' under an RG named 'MyResourceGroup'.
metadata:
  content_git_url: https://github.com/Azure/azure-powershell/blob/main/src/Resources/Resources/help/Get-AzResourceGroupDeploymentStack.md
  document type: cmdlet
  external help file: Microsoft.Azure.PowerShell.Cmdlets.ResourceManager.dll-Help.xml
  HelpUri: https://learn.microsoft.com/powershell/module/az.resources/Get-AzResourceGroupDeploymentStack
  Module Name: Az.Resources
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/main/src/Resources/Resources/help/Get-AzResourceGroupDeploymentStack.md
  PlatyPS schema version: 2024-05-01
