### YamlMime:PowerShellCmdlet1
uid: Az.Resources.Get-AzManagementGroupDeployment
name: Get-AzManagementGroupDeployment
module: Az.Resources
isPreview: false
summary: |-
  Get deployment at a management group
description: |-
  The **Get-AzManagementGroupDeployment** cmdlet gets the deployments at the a management group.
  Specify the *Name* or *Id* parameter to filter the results.
  By default, **Get-AzManagementGroupDeployment** gets all deployments at the management group.
parameters:
  cmdletParameters:
  - name: DefaultProfile
    type: <xref href="Microsoft.Azure.Commands.Common.Authentication.Abstractions.Core.IAzureContextContainer" data-throw-if-not-resolved="False" />
    description: |-
      The credentials, account, tenant, and subscription used for communication with Azure.
    aliases:
    - AzContext
    - AzureRmContext
    - AzureCredential
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: Id
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      The fully qualified resource Id of the deployment.
      example: /providers/Microsoft.Management/managementGroups/{managementGroupId}/providers/Microsoft.Resources/deployments/{deploymentName}
    aliases:
    - DeploymentId
    - ResourceId
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: GetByDeploymentId
      position: Named
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: ManagementGroupId
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      The management group id.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: GetByDeploymentName
      position: "0"
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: Name
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      The name of deployment.
    aliases:
    - DeploymentName
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: GetByDeploymentName
      position: "1"
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: Pre
    type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
    description: |-
      When set, indicates that the cmdlet should use pre-release API versions when automatically determining which version to use.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  commonParameters: |-
    This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable,
    -InformationAction, -InformationVariable, -OutBuffer, -OutVariable, -PipelineVariable,
    -ProgressAction, -Verbose, -WarningAction, and -WarningVariable. For more information, see
    [about_CommonParameters](https://go.microsoft.com/fwlink/?LinkID=113216).
syntaxes:
- syntax: |-
    ```Syntax
    Get-AzManagementGroupDeployment
        [-ManagementGroupId] <String>
        [[-Name] <String>]
        [-Pre]
        [-DefaultProfile <IAzureContextContainer>]
        [<CommonParameters>]
    ```
  parameterSetName: GetByDeploymentName
  isDefault: true
- syntax: |-
    ```Syntax
    Get-AzManagementGroupDeployment
        -Id <String>
        [-Pre]
        [-DefaultProfile <IAzureContextContainer>]
        [<CommonParameters>]
    ```
  parameterSetName: GetByDeploymentId
  isDefault: false
inputs:
- name: <xref href="None" data-throw-if-not-resolved="False" />
outputs:
- name: <xref href="Microsoft.Azure.Commands.ResourceManager.Cmdlets.SdkModels.PSDeployment" data-throw-if-not-resolved="False" />
examples:
- title: 'Example 1: Get all deployments at a management group'
  description: |-
    ```powershell
    Get-AzManagementGroupDeployment -ManagementGroupId "myMG"
    ```

    This command gets all deployments at the management group "myMG".
- title: 'Example 2: Get a deployment by name'
  description: |-
    ```powershell
    Get-AzManagementGroupDeployment -ManagementGroupId "myMG" -Name "Deploy01"
    ```

    This command gets the "Deploy01" deployment at the management group "myMG".
    You can assign a name to a deployment when you create it by using the **New-AzManagementGroupDeployment** cmdlets.
    If you do not assign a name, the cmdlets provide a default name based on the template that is used to create the deployment.
- title: 'Example 3: Get a deployment by ID'
  description: |-
    ```powershell
    Get-AzDeployment -Id "/providers/Microsoft.Management/managementGroups/myMG/providers/Microsoft.Resources/deployments/Deploy01"
    ```

    This command gets the "Deploy01" deployment at the management group "myMG".
metadata:
  content_git_url: https://github.com/Azure/azure-powershell/blob/main/src/Resources/Resources/help/Get-AzManagementGroupDeployment.md
  document type: cmdlet
  external help file: Microsoft.Azure.PowerShell.Cmdlets.ResourceManager.dll-Help.xml
  HelpUri: https://learn.microsoft.com/powershell/module/az.resources/get-azmanagementgroupdeployment
  Module Name: Az.Resources
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/main/src/Resources/Resources/help/Get-AzManagementGroupDeployment.md
  PlatyPS schema version: 2024-05-01
