### YamlMime:PowerShellCmdlet1
uid: Azure.Get-AzureDeploymentEvent
name: Get-AzureDeploymentEvent
module: Azure
isPreview: false
summary: |-
  Gets information about events that Azure initiates that impact virtual machines and cloud services.

  [!INCLUDE [rdfe-banner](../../includes/rdfe-banner.md)]
description: |-
  The **Get-AzureDeploymentEvent** cmdlet gets information regarding events that Azure initiates that impact virtual machines and cloud services.
  These events include planned maintenance events.
  This cmdlet returns a list of events that identify the role instance or virtual machine impacted, the reason for the impact, and the start time of the event.
parameters:
  cmdletParameters:
  - name: DeploymentName
    type: <xref href="String" data-throw-if-not-resolved="False" />
    description: |-
      Specifies the name of the deployment for which this cmdlet gets events.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: GetDeploymentEventByName
      position: "1"
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: EndTime
    type: <xref href="DateTime" data-throw-if-not-resolved="False" />
    description: |-
      Specifies the ending time for the scheduled events that this cmdlet gets.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: "2"
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: InformationAction
    type: <xref href="ActionPreference" data-throw-if-not-resolved="False" />
    description: |-
      Specifies how this cmdlet responds to an information event.

      The acceptable values for this parameter are:

      - Continue
      - Ignore
      - Inquire
      - SilentlyContinue
      - Stop
      - Suspend
    aliases:
    - infa
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: InformationVariable
    type: <xref href="String" data-throw-if-not-resolved="False" />
    description: |-
      Specifies an information variable.
    aliases:
    - iv
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: Profile
    type: <xref href="AzureSMProfile" data-throw-if-not-resolved="False" />
    description: |-
      Specifies the Azure profile from which this cmdlet reads.
      If you do not specify a profile, this cmdlet reads from the local default profile.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: ServiceName
    type: <xref href="String" data-throw-if-not-resolved="False" />
    description: |-
      Specifies the name of the hosted service for which this cmdlet gets scheduled events.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: "0"
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: true
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: Slot
    type: <xref href="String" data-throw-if-not-resolved="False" />
    description: |-
      Specifies the environment of the deployment for which this cmdlet gets scheduled events.
      Valid values are: Staging and Production.
      The default value is Production.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: GetDeploymentEventBySlot
      position: "3"
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: StartTime
    type: <xref href="DateTime" data-throw-if-not-resolved="False" />
    description: |-
      Specifies the starting time for the scheduled events that this cmdlet gets.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: "1"
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  commonParameters: |-
    This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable,
    -InformationAction, -InformationVariable, -OutBuffer, -OutVariable, -PipelineVariable,
    -ProgressAction, -Verbose, -WarningAction, and -WarningVariable. For more information, see
    [about_CommonParameters](https://go.microsoft.com/fwlink/?LinkID=113216).
syntaxes:
- syntax: |-
    ```Syntax
    Get-AzureDeploymentEvent
        [-ServiceName] <String>
        [-StartTime] <DateTime>
        [-EndTime] <DateTime>
        [[-Slot] <String>]
        [-Profile <AzureSMProfile>]
        [-InformationAction <ActionPreference>]
        [-InformationVariable <String>]
        [<CommonParameters>]
    ```
  parameterSetName: GetDeploymentEventBySlot
  isDefault: true
- syntax: |-
    ```Syntax
    Get-AzureDeploymentEvent
        [-ServiceName] <String>
        [-StartTime] <DateTime>
        [-EndTime] <DateTime>
        [-DeploymentName] <String>
        [-Profile <AzureSMProfile>]
        [-InformationAction <ActionPreference>]
        [-InformationVariable <String>]
        [<CommonParameters>]
    ```
  parameterSetName: GetDeploymentEventByName
  isDefault: false
examples:
- title: '1:'
  description: |-
    ```
    Get-AzureDeploymentEvent -DeploymentName "ContosoDeployment" -ServiceName "ContosoService"
    ```
links:
- text: Get-AzureDeployment
  href: ./Get-AzureDeployment.yml
metadata:
  document type: cmdlet
  external help file: Microsoft.WindowsAzure.Commands.ServiceManagement.dll-Help.xml
  HelpUri: 
  Module Name: Azure
  ms.assetid: 6715B3E8-6880-4B86-B831-41664766E12B
  PlatyPS schema version: 2024-05-01
