### YamlMime:PowerShellCmdlet1
uid: Azure.Get-AzureAclConfig
name: Get-AzureAclConfig
module: Azure
isPreview: false
summary: |-
  Gets the ACL configuration object from an Azure virtual machine.

  [!INCLUDE [rdfe-banner](../../includes/rdfe-banner.md)]
description: |-
  The **Get-AzureAclConfig** cmdlet gets the access control list (ACL) configuration object from an existing Azure virtual machine.
parameters:
  cmdletParameters:
  - name: EndpointName
    type: <xref href="String" data-throw-if-not-resolved="False" />
    description: |-
      Specifies the name of the endpoint for which this cmdlet gets an ACL.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: "0"
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: InformationAction
    type: <xref href="ActionPreference" data-throw-if-not-resolved="False" />
    description: |-
      Specifies how this cmdlet responds to an information event.

      The acceptable values for this parameter are:

      - Continue
      - Ignore
      - Inquire
      - SilentlyContinue
      - Stop
      - Suspend
    aliases:
    - infa
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: InformationVariable
    type: <xref href="String" data-throw-if-not-resolved="False" />
    description: |-
      Specifies an information variable.
    aliases:
    - iv
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: Profile
    type: <xref href="AzureSMProfile" data-throw-if-not-resolved="False" />
    description: |-
      Specifies the Azure profile from which this cmdlet reads.
      If you do not specify a profile, this cmdlet reads from the local default profile.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: VM
    type: <xref href="IPersistentVM" data-throw-if-not-resolved="False" />
    description: |-
      Specifies the virtual machine object for which this cmdlet gets ACL configuration.
    aliases:
    - InputObject
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: true
      valueFromPipeline: true
      valueFromPipelineByPropertyName: true
      valueFromRemainingArguments: false
    supportsWildcards: false
  commonParameters: |-
    This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable,
    -InformationAction, -InformationVariable, -OutBuffer, -OutVariable, -PipelineVariable,
    -ProgressAction, -Verbose, -WarningAction, and -WarningVariable. For more information, see
    [about_CommonParameters](https://go.microsoft.com/fwlink/?LinkID=113216).
syntaxes:
- syntax: |-
    ```Syntax
    Get-AzureAclConfig
        [[-EndpointName] <String>]
        -VM <IPersistentVM>
        [-Profile <AzureSMProfile>]
        [-InformationAction <ActionPreference>]
        [-InformationVariable <String>]
        [<CommonParameters>]
    ```
  parameterSetName: Default
  isDefault: true
examples:
- title: 'Example 1: Get an ACL configuration object for a virtual machine endpoint'
  description: |-
    ```
    PS C:\> $Acl = Get-AzureVM -ServiceName "ContosoService" -Name "VirtualMachine07" | Get-AzureAclConfig -EndpointName "Web"
    ```

    The first command gets the virtual machine named VirtualMachine07 in the service named ContosoService by using the **Get-AzureVM** cmdlet.
    The command passes that object to the **Get-AzureAclConfig** cmdlet by using the pipeline operator.
    That cmdlet gets the ACL configuration for the endpoint named Web.
    The command stores that ACL configuration object in the $Acl variable.
links:
- text: Get-AzureVM
  href: ./Get-AzureVM.yml
- text: New-AzureAclConfig
  href: ./New-AzureAclConfig.yml
- text: Remove-AzureAclConfig
  href: ./Remove-AzureAclConfig.yml
- text: Set-AzureAclConfig
  href: ./Set-AzureAclConfig.yml
metadata:
  document type: cmdlet
  external help file: Microsoft.WindowsAzure.Commands.ServiceManagement.dll-Help.xml
  HelpUri: 
  Module Name: Azure
  ms.assetid: 0A32348E-C38D-4555-8F7C-6515F4EE7F23
  PlatyPS schema version: 2024-05-01
