### YamlMime:PowerShellCmdlet1
uid: Azure.New-AzureDeployment
name: New-AzureDeployment
module: Azure
isPreview: false
summary: |-
  Creates a deployment from a service.

  [!INCLUDE [rdfe-banner](../../includes/rdfe-banner.md)]

  [!INCLUDE [rdfe-deprecation-banner](../../includes/rdfe-deprecation-banner.md)]
description: |-
  The **New-AzureDeployment** cmdlet creates an Azure deployment from a service that comprises web roles and worker roles.
  This cmdlet creates a deployment based on a package file (.cspkg) and a service configuration file (.cscfg).
  Specify a name that is unique within deployment environment.

  Use the **New-AzureVM** cmdlet to create a deployment based on Azure virtual machines.
parameters:
  cmdletParameters:
  - name: Configuration
    type: <xref href="String" data-throw-if-not-resolved="False" />
    description: |-
      Specifies the full path of a service configuration file.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: "2"
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: DoNotStart
    type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
    description: |-
      Specifies that this cmdlet does not start the deployment.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: ExtensionConfiguration
    type: <xref href="ExtensionConfigurationInput" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
    description: |-
      Specifies an array of extension configuration objects.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: true
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: InformationAction
    type: <xref href="ActionPreference" data-throw-if-not-resolved="False" />
    description: |-
      Specifies how this cmdlet responds to an information event.

      The acceptable values for this parameter are:

      - Continue
      - Ignore
      - Inquire
      - SilentlyContinue
      - Stop
      - Suspend
    aliases:
    - infa
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: InformationVariable
    type: <xref href="String" data-throw-if-not-resolved="False" />
    description: |-
      Specifies an information variable.
    aliases:
    - iv
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: Label
    type: <xref href="String" data-throw-if-not-resolved="False" />
    description: |-
      Specifies a label name for the deployment.
      If you do not specify a label, this cmdlet uses a GUID.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: "4"
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: Name
    type: <xref href="String" data-throw-if-not-resolved="False" />
    description: |-
      Specifies a deployment name.
      If you do not specify a name, this cmdlet uses a GUID.
    aliases:
    - DeploymentName
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: "5"
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: Package
    type: <xref href="String" data-throw-if-not-resolved="False" />
    description: |-
      Specifies the path or URI of a .cspkg file in storage within the same subscription or project.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: "1"
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: Profile
    type: <xref href="AzureSMProfile" data-throw-if-not-resolved="False" />
    description: |-
      Specifies the Azure profile from which this cmdlet reads.
      If you do not specify a profile, this cmdlet reads from the local default profile.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: ServiceName
    type: <xref href="String" data-throw-if-not-resolved="False" />
    description: |-
      Specifies the name of the Azure service for the deployment.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: "0"
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: true
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: Slot
    type: <xref href="String" data-throw-if-not-resolved="False" />
    description: |-
      Specifies the environment where this cmdlet creates the deployment.
      Valid values are: Staging and Production.
      The default value is Production.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: "3"
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: true
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: TreatWarningsAsError
    type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
    description: |-
      Specifies that warning messages are errors.
      If you specify this parameter, a warning message causes the deployment to fail.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  commonParameters: |-
    This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable,
    -InformationAction, -InformationVariable, -OutBuffer, -OutVariable, -PipelineVariable,
    -ProgressAction, -Verbose, -WarningAction, and -WarningVariable. For more information, see
    [about_CommonParameters](https://go.microsoft.com/fwlink/?LinkID=113216).
syntaxes:
- syntax: |-
    ```Syntax
    New-AzureDeployment
        [-ServiceName] <String>
        [-Package] <String>
        [-Configuration] <String>
        [-Slot] <String>
        [[-Label] <String>]
        [[-Name] <String>]
        [-DoNotStart]
        [-TreatWarningsAsError]
        [-ExtensionConfiguration <ExtensionConfigurationInput[]>]
        [-Profile <AzureSMProfile>]
        [-InformationAction <ActionPreference>]
        [-InformationVariable <String>]
        [<CommonParameters>]
    ```
  parameterSetName: Default
  isDefault: true
examples:
- title: 'Example 1: Create a deployment'
  description: |-
    ```
    PS C:\> New-AzureDeployment -ServiceName "ContosoService" -Slot "Production" -Package "https://contosostorage.blob.core.windows.net/container06/ContosoPackage.cspkg" -Configuration "C:\packages\ContosoConfiguration.cscfg" -Label "ContosoDeployment"
    ```

    This command creates a production deployment based on a package named ContosoPackage.cspkg and a configuration named ContosoConfiguration.cscfg.
    The command specifies a label for the deployment.
    It does not specify a name.
    This cmdlet creates a GUID as the name.
- title: 'Example 2: Create a deployment based on an extension configuration'
  description: |-
    ```
    PS C:\> New-AzureDeployment -ServiceName "ContosoService" -Slot "Production" -Package "https://contosostorage.blob.core.windows.net/container06/ContosoPackage.cspkg" -Configuration "C:\packages\ContosoConfiguration.cscfg" -ExtensionConfiguration "C:\packages\ContosoExtensionConfig.cscfg"
    ```

    This command creates a production deployment based on a package and configuration.
    The command specifies an extension configuration named ContosoExtensionConfig.cscfg.
    This cmdlet creates GUIDs as the name and the label.
links:
- text: Get-AzureDeployment
  href: ./Get-AzureDeployment.yml
- text: Get-AzureDeploymentEvent
  href: ./Get-AzureDeploymentEvent.yml
- text: Move-AzureDeployment
  href: ./Move-AzureDeployment.yml
- text: New-AzureVM
  href: ./New-AzureVM.yml
- text: Remove-AzureDeployment
  href: ./Remove-AzureDeployment.yml
- text: Set-AzureDeployment
  href: ./Set-AzureDeployment.yml
metadata:
  document type: cmdlet
  external help file: Microsoft.WindowsAzure.Commands.ServiceManagement.dll-Help.xml
  HelpUri: 
  Module Name: Azure
  ms.assetid: 2BDB255A-EFB3-4580-BE95-187008DB208C
  PlatyPS schema version: 2024-05-01
