### YamlMime:PowerShellCmdlet1
uid: Azure.New-AzureServiceRemoteDesktopExtensionConfig
name: New-AzureServiceRemoteDesktopExtensionConfig
module: Azure
isPreview: false
summary: |-
  Generates a remote desktop extension configuration for a deployment.

  [!INCLUDE [rdfe-banner](../../includes/rdfe-banner.md)]
description: |-
  The **New-AzureServiceRemoteDesktopExtensionConfig** cmdlet generates a configuration for a remote desktop extension for a deployment.
parameters:
  cmdletParameters:
  - name: CertificateThumbprint
    type: <xref href="String" data-throw-if-not-resolved="False" />
    description: |-
      Specifies a certificate thumbprint to use to encrypt the private configuration.
      This certificate has to already exist in the certificate store.
      If you do not specify a certificate, this cmdlet creates a certificate.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: NewExtensionUsingThumbprint
      position: "1"
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: true
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: Credential
    type: <xref href="PSCredential" data-throw-if-not-resolved="False" />
    description: |-
      Specifies the credentials to enable for remote desktop.
      Credentials include a user name and password.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: "3"
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: true
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: Expiration
    type: <xref href="DateTime" data-throw-if-not-resolved="False" />
    description: |-
      Specifies a **DateTime** object that allows the user to specify when the user account expires.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: "4"
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: true
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: ExtensionId
    type: <xref href="String" data-throw-if-not-resolved="False" />
    description: |-
      Specifies the extension ID.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: "6"
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: true
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: InformationAction
    type: <xref href="ActionPreference" data-throw-if-not-resolved="False" />
    description: |-
      Specifies how this cmdlet responds to an information event.

      The acceptable values for this parameter are:

      - Continue
      - Ignore
      - Inquire
      - SilentlyContinue
      - Stop
      - Suspend
    aliases:
    - infa
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: InformationVariable
    type: <xref href="String" data-throw-if-not-resolved="False" />
    description: |-
      Specifies an information variable.
    aliases:
    - iv
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: Profile
    type: <xref href="AzureSMProfile" data-throw-if-not-resolved="False" />
    description: |-
      Specifies the Azure profile from which this cmdlet reads.
      If you do not specify a profile, this cmdlet reads from the local default profile.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: Role
    type: <xref href="String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
    description: |-
      Specifies an optional array of roles for which to specify the remote desktop configuration.
      If this parameter is not specified the remote desktop configuration is applied as the default configuration for all roles.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: "0"
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: true
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: ThumbprintAlgorithm
    type: <xref href="String" data-throw-if-not-resolved="False" />
    description: |-
      Specifies a thumbprint hashing algorithm which is used with the thumbprint to identify the certificate.
      This parameter is optional and the default is sha1.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: "2"
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: true
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: Version
    type: <xref href="String" data-throw-if-not-resolved="False" />
    description: |-
      Specifies the extension version.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: "5"
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: true
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: X509Certificate
    type: <xref href="X509Certificate2" data-throw-if-not-resolved="False" />
    description: |-
      Specifies an x509 certificate that when specified will be automatically uploaded to the cloud service and used for encrypting the extension private configuration.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: NewExtension
      position: "1"
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: true
      valueFromRemainingArguments: false
    supportsWildcards: false
  commonParameters: |-
    This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable,
    -InformationAction, -InformationVariable, -OutBuffer, -OutVariable, -PipelineVariable,
    -ProgressAction, -Verbose, -WarningAction, and -WarningVariable. For more information, see
    [about_CommonParameters](https://go.microsoft.com/fwlink/?LinkID=113216).
syntaxes:
- syntax: |-
    ```Syntax
    New-AzureServiceRemoteDesktopExtensionConfig
        [[-Role] <String[]>]
        [[-X509Certificate] <X509Certificate2>]
        [[-ThumbprintAlgorithm] <String>]
        [-Credential] <PSCredential>
        [[-Expiration] <DateTime>]
        [[-Version] <String>]
        [[-ExtensionId] <String>]
        [-Profile <AzureSMProfile>]
        [-InformationAction <ActionPreference>]
        [-InformationVariable <String>]
        [<CommonParameters>]
    ```
  parameterSetName: NewExtension
  isDefault: true
- syntax: |-
    ```Syntax
    New-AzureServiceRemoteDesktopExtensionConfig
        [[-Role] <String[]>]
        [-CertificateThumbprint] <String>
        [[-ThumbprintAlgorithm] <String>]
        [-Credential] <PSCredential>
        [[-Expiration] <DateTime>]
        [[-Version] <String>]
        [[-ExtensionId] <String>]
        [-Profile <AzureSMProfile>]
        [-InformationAction <ActionPreference>]
        [-InformationVariable <String>]
        [<CommonParameters>]
    ```
  parameterSetName: NewExtensionUsingThumbprint
  isDefault: false
examples:
- title: 'Example 1: Generate a remote desktop extension configuration'
  description: |-
    ```
    PS C:\> $rdpConfig = New-AzureServiceRemoteDesktopExtensionConfig -Credential $cred
    ```

    This command generates a remote desktop extension configuration for the specified credentials.
- title: 'Example 2: Generate a remote desktop extension configuration for a specified role'
  description: |-
    ```
    PS C:\> $rdpConfig = New-AzureServiceRemoteDesktopExtensionConfig -Credential $cred -Role "WebRole01"
    ```

    This command generates a remote desktop extension configuration for the specified credentials and the WebRole01 role.
links:
- text: Set-AzureServiceRemoteDesktopExtension
  href: ./Set-AzureServiceRemoteDesktopExtension.yml
metadata:
  document type: cmdlet
  external help file: Microsoft.WindowsAzure.Commands.ServiceManagement.dll-Help.xml
  HelpUri: 
  Module Name: Azure
  ms.assetid: 2563898E-C4A0-4530-AB46-30A6FC1BE55C
  PlatyPS schema version: 2024-05-01
