### YamlMime:PowerShellCmdlet1
uid: Azure.New-AzureVMSqlServerKeyVaultCredentialConfig
name: New-AzureVMSqlServerKeyVaultCredentialConfig
module: Azure
isPreview: false
summary: |-
  [!INCLUDE [rdfe-banner](../../includes/rdfe-banner.md)]
parameters:
  cmdletParameters:
  - name: AzureKeyVaultUrl
    type: <xref href="String" data-throw-if-not-resolved="False" />
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: "0"
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: true
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: CredentialName
    type: <xref href="String" data-throw-if-not-resolved="False" />
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: "0"
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: true
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: Enable
    type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: "0"
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: true
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: InformationAction
    type: <xref href="ActionPreference" data-throw-if-not-resolved="False" />
    description: |-
      Specifies how this cmdlet responds to an information event.

      The acceptable values for this parameter are:

      - Continue
      - Ignore
      - Inquire
      - SilentlyContinue
      - Stop
      - Suspend
    aliases:
    - infa
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: InformationVariable
    type: <xref href="String" data-throw-if-not-resolved="False" />
    description: |-
      Specifies an information variable.
    aliases:
    - iv
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: Profile
    type: <xref href="AzureSMProfile" data-throw-if-not-resolved="False" />
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: ServicePrincipalName
    type: <xref href="String" data-throw-if-not-resolved="False" />
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: "0"
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: true
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: ServicePrincipalSecret
    type: <xref href="SecureString" data-throw-if-not-resolved="False" />
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: "0"
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: true
      valueFromRemainingArguments: false
    supportsWildcards: false
  commonParameters: |-
    This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable,
    -InformationAction, -InformationVariable, -OutBuffer, -OutVariable, -PipelineVariable,
    -ProgressAction, -Verbose, -WarningAction, and -WarningVariable. For more information, see
    [about_CommonParameters](https://go.microsoft.com/fwlink/?LinkID=113216).
syntaxes:
- syntax: |-
    ```Syntax
    New-AzureVMSqlServerKeyVaultCredentialConfig
        [-Enable]
        [[-CredentialName] <String>]
        [[-AzureKeyVaultUrl] <String>]
        [[-ServicePrincipalName] <String>]
        [[-ServicePrincipalSecret] <SecureString>]
        [-Profile <AzureSMProfile>]
        [-InformationAction <ActionPreference>]
        [-InformationVariable <String>]
        [<CommonParameters>]
    ```
  parameterSetName: Default
  isDefault: true
examples:
- title: '1:'
  description: |-
    ```
    PS C:\>
    ```
metadata:
  document type: cmdlet
  external help file: Microsoft.WindowsAzure.Commands.ServiceManagement.dll-Help.xml
  HelpUri: 
  Module Name: Azure
  ms.assetid: EC6F7790-5E31-4C22-B006-38B5C1868671
  PlatyPS schema version: 2024-05-01
