### YamlMime:PowerShellCmdlet1
uid: Az.ContainerInstance.New-AzContainerInstanceEnvironmentVariableObject
name: New-AzContainerInstanceEnvironmentVariableObject
module: Az.ContainerInstance
isPreview: false
summary: |-
  Create a in-memory object for EnvironmentVariable
description: |-
  Create a in-memory object for EnvironmentVariable
parameters:
  cmdletParameters:
  - name: Name
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      The name of the environment variable.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: SecureValue
    type: <xref href="System.Security.SecureString" data-throw-if-not-resolved="False" />
    description: |-
      The value of the secure environment variable.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: Value
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      The value of the environment variable.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  commonParameters: |-
    This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable,
    -InformationAction, -InformationVariable, -OutBuffer, -OutVariable, -PipelineVariable,
    -ProgressAction, -Verbose, -WarningAction, and -WarningVariable. For more information, see
    [about_CommonParameters](https://go.microsoft.com/fwlink/?LinkID=113216).
syntaxes:
- syntax: |-
    ```Syntax
    New-AzContainerInstanceEnvironmentVariableObject
        -Name <String>
        [-SecureValue <SecureString>]
        [-Value <String>]
        [<CommonParameters>]
    ```
  parameterSetName: Default
  isDefault: true
outputs:
- name: <xref href="Microsoft.Azure.PowerShell.Cmdlets.ContainerInstance.Models.Api20240501Preview.EnvironmentVariable" data-throw-if-not-resolved="False" />
examples:
- title: 'Example 1: Create an environment variable within a container instance'
  description: |-
    ```powershell
    New-AzContainerInstanceEnvironmentVariableObject -Name "env1" -Value "value1"
    ```

    ```output
    Name SecureValue Value
    ---- ----------- -----
    env1             value1
    ```

    This command creates an environment variable within a container instance.
- title: 'Example 2: Create a secure environment variable within a container instance'
  description: |-
    ```powershell
    $pwd = ConvertTo-SecureString -String "****" -AsPlainText -Force
    New-AzContainerInstanceEnvironmentVariableObject -Name "env2" -SecureValue $pwd
    ```

    ```output
    Name SecureValue Value
    ---- ----------- -----
    env2 ******
    ```

    This command creates a secure environment variable within a container instance
metadata:
  content_git_url: https://github.com/Azure/azure-powershell/blob/main/src/ContainerInstance/ContainerInstance/help/New-AzContainerInstanceEnvironmentVariableObject.md
  document type: cmdlet
  external help file: Az.ContainerInstance-help.xml
  HelpUri: https://learn.microsoft.com/powershell/module/az.ContainerInstance/new-AzContainerInstanceEnvironmentVariableObject
  Module Name: Az.ContainerInstance
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/main/src/ContainerInstance/ContainerInstance/help/New-AzContainerInstanceEnvironmentVariableObject.md
  PlatyPS schema version: 2024-05-01
