### YamlMime:PowerShellCmdlet1
uid: Az.Network.Get-AzExpressRoutePortLinkConfig
name: Get-AzExpressRoutePortLinkConfig
module: Az.Network
isPreview: false
summary: |-
  Gets an ExpressRoutePort link configuration.
description: |-
  The **Get-AzExpressRoutePortLinkConfig** cmdlet retrieves the configuration of a link
  of an ExpressRoutePort.
parameters:
  cmdletParameters:
  - name: DefaultProfile
    type: <xref href="Microsoft.Azure.Commands.Common.Authentication.Abstractions.Core.IAzureContextContainer" data-throw-if-not-resolved="False" />
    description: |-
      The credentials, account, tenant, and subscription used for communication with Azure.
    aliases:
    - AzContext
    - AzureRmContext
    - AzureCredential
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: ExpressRoutePort
    type: <xref href="Microsoft.Azure.Commands.Network.Models.PSExpressRoutePort" data-throw-if-not-resolved="False" />
    description: |-
      The reference of the ExpressRoutePort resource.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: true
      valueFromPipeline: true
      valueFromPipelineByPropertyName: true
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: Name
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      Name of the link.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: ResourceNameParameterSet
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: ResourceId
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      ResourceId of the link.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: ResourceIdParameterSet
      position: Named
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: true
      valueFromRemainingArguments: false
    supportsWildcards: false
  commonParameters: |-
    This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable,
    -InformationAction, -InformationVariable, -OutBuffer, -OutVariable, -PipelineVariable,
    -ProgressAction, -Verbose, -WarningAction, and -WarningVariable. For more information, see
    [about_CommonParameters](https://go.microsoft.com/fwlink/?LinkID=113216).
syntaxes:
- syntax: |-
    ```Syntax
    Get-AzExpressRoutePortLinkConfig
        -ExpressRoutePort <PSExpressRoutePort>
        [-Name <String>]
        [-DefaultProfile <IAzureContextContainer>]
        [<CommonParameters>]
    ```
  parameterSetName: ResourceNameParameterSet
  isDefault: true
- syntax: |-
    ```Syntax
    Get-AzExpressRoutePortLinkConfig
        -ResourceId <String>
        -ExpressRoutePort <PSExpressRoutePort>
        [-DefaultProfile <IAzureContextContainer>]
        [<CommonParameters>]
    ```
  parameterSetName: ResourceIdParameterSet
  isDefault: false
inputs:
- name: <xref href="System.String" data-throw-if-not-resolved="False" />
- name: <xref href="Microsoft.Azure.Commands.Network.Models.PSExpressRoutePort" data-throw-if-not-resolved="False" />
outputs:
- name: <xref href="Microsoft.Azure.Commands.Network.Models.PSExpressRouteLink" data-throw-if-not-resolved="False" />
examples:
- title: Example 1
  description: |-
    ```powershell
    Get-AzExpressRoutePortLinkConfig -ExpressRoutePort $erport -Name Link1
    ```

    Gets the Link1 configuration of ExpressRoutePort $erport
- title: Example 2
  description: |-
    ```powershell
    Get-AzExpressRoutePortLinkConfig -ExpressRoutePort $erport -ResourceId $id
    ```

    Gets the configuration of link with ResourceId $id in ExpressRoutePort $erport
metadata:
  content_git_url: https://github.com/Azure/azure-powershell/blob/main/src/Network/Network/help/Get-AzExpressRoutePortLinkConfig.md
  document type: cmdlet
  external help file: Microsoft.Azure.PowerShell.Cmdlets.Network.dll-Help.xml
  HelpUri: https://learn.microsoft.com/powershell/module/az.network/get-azexpressrouteportlinkconfig
  Module Name: Az.Network
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/main/src/Network/Network/help/Get-AzExpressRoutePortLinkConfig.md
  PlatyPS schema version: 2024-05-01
