### YamlMime:PowerShellCmdlet1
uid: Az.Network.Get-AzApplicationGatewayIPConfiguration
name: Get-AzApplicationGatewayIPConfiguration
module: Az.Network
isPreview: false
summary: |-
  Gets the IP configuration of an application gateway.
description: |-
  The **Get-AzApplicationGatewayIPConfiguration** cmdlet gets the IP configuration of an application gateway.
  The IP configuration contains the subnet in which the application gateway is deployed.
parameters:
  cmdletParameters:
  - name: ApplicationGateway
    type: <xref href="Microsoft.Azure.Commands.Network.Models.PSApplicationGateway" data-throw-if-not-resolved="False" />
    description: |-
      Specifies the application gateway object that contains IP configuration.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: true
      valueFromPipeline: true
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: DefaultProfile
    type: <xref href="Microsoft.Azure.Commands.Common.Authentication.Abstractions.Core.IAzureContextContainer" data-throw-if-not-resolved="False" />
    description: |-
      The credentials, account, tenant, and subscription used for communication with azure.
    aliases:
    - AzContext
    - AzureRmContext
    - AzureCredential
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: Name
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      Specifies the name of the IP configuration which this cmdlet gets.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  commonParameters: |-
    This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable,
    -InformationAction, -InformationVariable, -OutBuffer, -OutVariable, -PipelineVariable,
    -ProgressAction, -Verbose, -WarningAction, and -WarningVariable. For more information, see
    [about_CommonParameters](https://go.microsoft.com/fwlink/?LinkID=113216).
syntaxes:
- syntax: |-
    ```Syntax
    Get-AzApplicationGatewayIPConfiguration
        [-Name <String>]
        -ApplicationGateway <PSApplicationGateway>
        [-DefaultProfile <IAzureContextContainer>]
        [<CommonParameters>]
    ```
  parameterSetName: Default
  isDefault: true
inputs:
- name: <xref href="Microsoft.Azure.Commands.Network.Models.PSApplicationGateway" data-throw-if-not-resolved="False" />
outputs:
- name: <xref href="Microsoft.Azure.Commands.Network.Models.PSApplicationGatewayIPConfiguration" data-throw-if-not-resolved="False" />
examples:
- title: 'Example 1: Get a specific IP configuration'
  description: |-
    ```powershell
    $AppGw = Get-AzApplicationGateway -Name "ApplicationGateway01" -ResourceGroupName "ResourceGroup01"
    $GatewaySubnet = Get-AzApplicationGatewayIPConfiguration -Name "GatewaySubnet01" -ApplicationGateway $AppGw
    ```

    The first command gets an application gateway and stores it in the $AppGw variable.The second command gets an IP configuration named GateSubnet01 from the gateway stored in $AppGw.
- title: 'Example 2: Get a list of IP configurations'
  description: |-
    ```powershell
    $AppGw = Get-AzApplicationGateway -Name "ApplicationGateway01" -ResourceGroupName "ResourceGroup01"
    $GatewaySubnets = Get-AzApplicationGatewayIPConfiguration -ApplicationGateway $AppGw
    ```

    The first command gets an application gateway and stores it in the $AppGw variable.The second command gets a list of all IP configurations.
links:
- text: Add-AzApplicationGatewayIPConfiguration
  href: ./Add-AzApplicationGatewayIPConfiguration.yml
- text: New-AzApplicationGatewayIPConfiguration
  href: ./New-AzApplicationGatewayIPConfiguration.yml
- text: Remove-AzApplicationGatewayIPConfiguration
  href: ./Remove-AzApplicationGatewayIPConfiguration.yml
- text: Set-AzApplicationGatewayIPConfiguration
  href: ./Set-AzApplicationGatewayIPConfiguration.yml
metadata:
  content_git_url: https://github.com/Azure/azure-powershell/blob/main/src/Network/Network/help/Get-AzApplicationGatewayIPConfiguration.md
  document type: cmdlet
  external help file: Microsoft.Azure.PowerShell.Cmdlets.Network.dll-Help.xml
  HelpUri: https://learn.microsoft.com/powershell/module/az.network/get-azapplicationgatewayipconfiguration
  Module Name: Az.Network
  ms.assetid: 35562212-283C-4BB2-8B12-C3617A6760D0
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/main/src/Network/Network/help/Get-AzApplicationGatewayIPConfiguration.md
  PlatyPS schema version: 2024-05-01
