### YamlMime:PowerShellCmdlet1
uid: Az.Network.Get-AzApplicationGatewayListener
name: Get-AzApplicationGatewayListener
module: Az.Network
isPreview: false
summary: |-
  Gets the TCP\TLS listener of an application gateway.
description: |-
  The **Get-AzApplicationGatewayListener** cmdlet gets the TCP\TLS listener of an application gateway.
parameters:
  cmdletParameters:
  - name: ApplicationGateway
    type: <xref href="Microsoft.Azure.Commands.Network.Models.PSApplicationGateway" data-throw-if-not-resolved="False" />
    description: |-
      The applicationGateway
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: true
      valueFromPipeline: true
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: DefaultProfile
    type: <xref href="Microsoft.Azure.Commands.Common.Authentication.Abstractions.Core.IAzureContextContainer" data-throw-if-not-resolved="False" />
    description: |-
      The credentials, account, tenant, and subscription used for communication with Azure.
    aliases:
    - AzContext
    - AzureRmContext
    - AzureCredential
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: Name
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      The name of the application gateway listener
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  commonParameters: |-
    This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable,
    -InformationAction, -InformationVariable, -OutBuffer, -OutVariable, -PipelineVariable,
    -ProgressAction, -Verbose, -WarningAction, and -WarningVariable. For more information, see
    [about_CommonParameters](https://go.microsoft.com/fwlink/?LinkID=113216).
syntaxes:
- syntax: |-
    ```Syntax
    Get-AzApplicationGatewayListener
        [-Name <String>]
        -ApplicationGateway <PSApplicationGateway>
        [-DefaultProfile <IAzureContextContainer>]
        [<CommonParameters>]
    ```
  parameterSetName: Default
  isDefault: true
inputs:
- name: <xref href="Microsoft.Azure.Commands.Network.Models.PSApplicationGateway" data-throw-if-not-resolved="False" />
outputs:
- name: <xref href="Microsoft.Azure.Commands.Network.Models.PSApplicationGatewayListener" data-throw-if-not-resolved="False" />
examples:
- title: 'Example 1: Get a specific TCP\TLS listener'
  description: |-
    ```powershell
    $Appgw = Get-AzApplicationGateway -Name "ApplicationGateway01" -ResourceGroupName "ResourceGroup01"
    $Listener = Get-AzApplicationGatewayListener -Name "Listener01" -ApplicationGateway $Appgw
    ```

    This command gets a TCP\TLS listener named Listener01.
- title: 'Example 2: Get a list of TCP\TLS listeners'
  description: |-
    ```powershell
    $Appgw = Get-AzApplicationGateway -Name "ApplicationGateway01" -ResourceGroupName "ResourceGroup01"
    $Listeners = Get-AzApplicationGatewayListener -ApplicationGateway $Appgw
    ```

    This command gets a list of TCP\TLS listeners.
links:
- text: Add-AzApplicationGatewayListener
  href: ./Add-AzApplicationGatewayListener.yml
- text: New-AzApplicationGatewayListener
  href: ./New-AzApplicationGatewayListener.yml
- text: Remove-AzApplicationGatewayListener
  href: ./Remove-AzApplicationGatewayListener.yml
- text: Set-AzApplicationGatewayListener
  href: ./Set-AzApplicationGatewayListener.yml
metadata:
  content_git_url: https://github.com/Azure/azure-powershell/blob/main/src/Network/Network/help/Get-AzApplicationGatewayListener.md
  document type: cmdlet
  external help file: Microsoft.Azure.PowerShell.Cmdlets.Network.dll-Help.xml
  HelpUri: https://learn.microsoft.com/powershell/module/az.network/get-azapplicationgatewaylistener
  Module Name: Az.Network
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/main/src/Network/Network/help/Get-AzApplicationGatewayListener.md
  PlatyPS schema version: 2024-05-01
