### YamlMime:PowerShellCmdlet1
uid: Az.Network.Get-AzLoadBalancerInboundNatPoolConfig
name: Get-AzLoadBalancerInboundNatPoolConfig
module: Az.Network
isPreview: false
summary: |-
  Gets one or more inbound NAT pool configurations from a load balancer.
description: |-
  The **Get-AzLoadBalancerInboundNatPoolConfig** cmdlet gets one or more inbound NAT pool configurations from a load balancer.
parameters:
  cmdletParameters:
  - name: DefaultProfile
    type: <xref href="Microsoft.Azure.Commands.Common.Authentication.Abstractions.Core.IAzureContextContainer" data-throw-if-not-resolved="False" />
    description: |-
      The credentials, account, tenant, and subscription used for communication with azure.
    aliases:
    - AzContext
    - AzureRmContext
    - AzureCredential
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: LoadBalancer
    type: <xref href="Microsoft.Azure.Commands.Network.Models.PSLoadBalancer" data-throw-if-not-resolved="False" />
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: true
      valueFromPipeline: true
      valueFromPipelineByPropertyName: true
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: Name
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  commonParameters: |-
    This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable,
    -InformationAction, -InformationVariable, -OutBuffer, -OutVariable, -PipelineVariable,
    -ProgressAction, -Verbose, -WarningAction, and -WarningVariable. For more information, see
    [about_CommonParameters](https://go.microsoft.com/fwlink/?LinkID=113216).
syntaxes:
- syntax: |-
    ```Syntax
    Get-AzLoadBalancerInboundNatPoolConfig
        -LoadBalancer <PSLoadBalancer>
        [-Name <String>]
        [-DefaultProfile <IAzureContextContainer>]
        [<CommonParameters>]
    ```
  parameterSetName: Default
  isDefault: true
inputs:
- name: <xref href="Microsoft.Azure.Commands.Network.Models.PSLoadBalancer" data-throw-if-not-resolved="False" />
outputs:
- name: <xref href="Microsoft.Azure.Commands.Network.Models.PSInboundNatPool" data-throw-if-not-resolved="False" />
examples:
- title: 'Example 1: Get'
  description: |-
    ```powershell
    $slb = Get-AzLoadBalancer -Name "MyLoadBalancer" -ResourceGroupName "MyResourceGroup"
    $slb | Get-AzLoadBalancerInboundNatPoolConfig -Name myInboundNatPool
    ```
links:
- text: Add-AzLoadBalancerInboundNatPoolConfig
  href: ./Add-AzLoadBalancerInboundNatPoolConfig.yml
- text: New-AzLoadBalancerInboundNatPoolConfig
  href: ./New-AzLoadBalancerInboundNatPoolConfig.yml
- text: Remove-AzLoadBalancerInboundNatPoolConfig
  href: ./Remove-AzLoadBalancerInboundNatPoolConfig.yml
- text: Set-AzLoadBalancerInboundNatPoolConfig
  href: ./Set-AzLoadBalancerInboundNatPoolConfig.yml
metadata:
  content_git_url: https://github.com/Azure/azure-powershell/blob/main/src/Network/Network/help/Get-AzLoadBalancerInboundNatPoolConfig.md
  document type: cmdlet
  external help file: Microsoft.Azure.PowerShell.Cmdlets.Network.dll-Help.xml
  HelpUri: https://learn.microsoft.com/powershell/module/az.network/get-azloadbalancerinboundnatpoolconfig
  Module Name: Az.Network
  ms.assetid: 614B0634-154A-449A-83E7-051DEF5A3BEE
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/main/src/Network/Network/help/Get-AzLoadBalancerInboundNatPoolConfig.md
  PlatyPS schema version: 2024-05-01
