### YamlMime:PowerShellCmdlet1
uid: Az.Network.Invoke-AzNetworkWatcherNetworkConfigurationDiagnostic
name: Invoke-AzNetworkWatcherNetworkConfigurationDiagnostic
module: Az.Network
isPreview: false
summary: |-
  Invoke network configuration diagnostic session for specified network profiles on target resource.
description: |-
  The Invoke-AzNetworkWatcherNetworkConfigurationDiagnostic cmdlet invoke network configuration diagnostic session for specified network profiles on target resource.
notes: |-
  Keywords: azure, azurerm, arm, resource, management, manager, network, networking, watcher, diagnostic, profile
parameters:
  cmdletParameters:
  - name: AsJob
    type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
    description: |-
      Run cmdlet in the background
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: DefaultProfile
    type: <xref href="Microsoft.Azure.Commands.Common.Authentication.Abstractions.Core.IAzureContextContainer" data-throw-if-not-resolved="False" />
    description: |-
      The credentials, account, tenant, and subscription used for communication with Azure.
    aliases:
    - AzContext
    - AzureRmContext
    - AzureCredential
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: Location
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      Location of the network watcher.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: SetByLocation
      position: Named
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: NetworkWatcher
    type: <xref href="Microsoft.Azure.Commands.Network.Models.PSNetworkWatcher" data-throw-if-not-resolved="False" />
    description: |-
      The network watcher resource.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: SetByResource
      position: Named
      isRequired: true
      valueFromPipeline: true
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: NetworkWatcherName
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      The name of network watcher.
    aliases:
    - Name
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: SetByName
      position: Named
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: Profile
    type: <xref href="System.Collections.Generic.List`1" data-throw-if-not-resolved="False" /><span>[</span><xref href="Microsoft.Azure.Commands.Network.Models.PSNetworkConfigurationDiagnosticProfile" data-throw-if-not-resolved="False" /><span>]</span>
    description: |-
      List of network configuration diagnostic profiles.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: ResourceGroupName
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      The name of the network watcher resource group.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: SetByName
      position: Named
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: ResourceId
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      Resource ID.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: SetByResourceId
      position: Named
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: true
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: TargetResourceId
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      The ID of the target resource to perform network configuration diagnostic.
      Valid options are VM, NetworkInterface, VMSS/NetworkInterface and Application Gateway.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: true
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: VerbosityLevel
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      Verbosity level.
      Accepted values are 'Normal', 'Minimum', 'Full'.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  commonParameters: |-
    This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable,
    -InformationAction, -InformationVariable, -OutBuffer, -OutVariable, -PipelineVariable,
    -ProgressAction, -Verbose, -WarningAction, and -WarningVariable. For more information, see
    [about_CommonParameters](https://go.microsoft.com/fwlink/?LinkID=113216).
syntaxes:
- syntax: |-
    ```Syntax
    Invoke-AzNetworkWatcherNetworkConfigurationDiagnostic
        -NetworkWatcher <PSNetworkWatcher>
        -TargetResourceId <String>
        -Profile <System.Collections.Generic.List`1[Microsoft.Azure.Commands.Network.Models.PSNetworkConfigurationDiagnosticProfile]>
        [-VerbosityLevel <String>]
        [-AsJob]
        [-DefaultProfile <IAzureContextContainer>]
        [<CommonParameters>]
    ```
  parameterSetName: SetByResource
  isDefault: true
- syntax: |-
    ```Syntax
    Invoke-AzNetworkWatcherNetworkConfigurationDiagnostic
        -NetworkWatcherName <String>
        -ResourceGroupName <String>
        -TargetResourceId <String>
        -Profile <System.Collections.Generic.List`1[Microsoft.Azure.Commands.Network.Models.PSNetworkConfigurationDiagnosticProfile]>
        [-VerbosityLevel <String>]
        [-AsJob]
        [-DefaultProfile <IAzureContextContainer>]
        [<CommonParameters>]
    ```
  parameterSetName: SetByName
  isDefault: false
- syntax: |-
    ```Syntax
    Invoke-AzNetworkWatcherNetworkConfigurationDiagnostic
        -Location <String>
        -TargetResourceId <String>
        -Profile <System.Collections.Generic.List`1[Microsoft.Azure.Commands.Network.Models.PSNetworkConfigurationDiagnosticProfile]>
        [-VerbosityLevel <String>]
        [-AsJob]
        [-DefaultProfile <IAzureContextContainer>]
        [<CommonParameters>]
    ```
  parameterSetName: SetByLocation
  isDefault: false
- syntax: |-
    ```Syntax
    Invoke-AzNetworkWatcherNetworkConfigurationDiagnostic
        -ResourceId <String>
        -TargetResourceId <String>
        -Profile <System.Collections.Generic.List`1[Microsoft.Azure.Commands.Network.Models.PSNetworkConfigurationDiagnosticProfile]>
        [-VerbosityLevel <String>]
        [-AsJob]
        [-DefaultProfile <IAzureContextContainer>]
        [<CommonParameters>]
    ```
  parameterSetName: SetByResourceId
  isDefault: false
inputs:
- name: <xref href="Microsoft.Azure.Commands.Network.Models.PSNetworkWatcher" data-throw-if-not-resolved="False" />
- name: <xref href="System.String" data-throw-if-not-resolved="False" />
outputs:
- name: <xref href="Microsoft.Azure.Commands.Network.Models.PSNetworkConfigurationDiagnosticResponse" data-throw-if-not-resolved="False" />
examples:
- title: 'Example 1: Invoke network configuration diagnostic session for VM and specified network profile'
  description: |-
    ```powershell
    $profile = New-AzNetworkWatcherNetworkConfigurationDiagnosticProfile -Direction Inbound -Protocol Tcp -Source 10.1.1.4 -Destination * -DestinationPort 50
    Invoke-AzNetworkWatcherNetworkConfigurationDiagnostic -Location eastus -TargetResourceId /subscriptions/61cc8a98-a8be-4bfe-a04e-0b461f93fe35/resourceGroups/NwRgEastUS/providers/Microsoft.Compute/virtualMachines/vm1 -Profile $profile
    ```

    ```output
    Results : [
                {
                  "Profile": {
                    "Direction": "Inbound",
                    "Protocol": "Tcp",
                    "Source": "10.1.1.4",
                    "Destination": "*",
                    "DestinationPort": "50"
                  },
                  "NetworkSecurityGroupResult": {
                    "SecurityRuleAccessResult": "Allow",
                    "EvaluatedNetworkSecurityGroups": [
                      {
                        "NetworkSecurityGroupId": "/subscriptions/61cc8a98-a8be-4bfe-a04e-0b461f93fe35/resourceGroups/clean
              upservice/providers/Microsoft.Network/networkSecurityGroups/rg-cleanupservice-nsg1",
                        "MatchedRule": {
                          "RuleName": "UserRule_Cleanuptool-Allow-4001",
                          "Action": "Allow"
                        },
                        "RulesEvaluationResult": [
                          {
                            "Name": "UserRule_Cleanuptool-Allow-100",
                            "ProtocolMatched": true,
                            "SourceMatched": false,
                            "SourcePortMatched": true,
                            "DestinationMatched": true,
                            "DestinationPortMatched": false
                          },
    ```
links:
- text: New-AzNetworkWatcher
  href: ./New-AzNetworkWatcher.yml
- text: Get-AzNetworkWatcher
  href: ./Get-AzNetworkWatcher.yml
- text: Remove-AzNetworkWatcher
  href: ./Remove-AzNetworkWatcher.yml
- text: Get-AzNetworkWatcherNextHop
  href: ./Get-AzNetworkWatcherNextHop.yml
- text: Get-AzNetworkWatcherSecurityGroupView
  href: ./Get-AzNetworkWatcherSecurityGroupView.yml
- text: Get-AzNetworkWatcherTopology
  href: ./Get-AzNetworkWatcherTopology.yml
- text: Start-AzNetworkWatcherResourceTroubleshooting
  href: ./Start-AzNetworkWatcherResourceTroubleshooting.yml
- text: New-AzNetworkWatcherPacketCapture
  href: ./New-AzNetworkWatcherPacketCapture.yml
- text: New-AzPacketCaptureFilterConfig
  href: ./New-AzPacketCaptureFilterConfig.yml
- text: Get-AzNetworkWatcherPacketCapture
  href: ./Get-AzNetworkWatcherPacketCapture.yml
- text: Remove-AzNetworkWatcherPacketCapture
  href: ./Remove-AzNetworkWatcherPacketCapture.yml
- text: Stop-AzNetworkWatcherPacketCapture
  href: ./Stop-AzNetworkWatcherPacketCapture.yml
- text: New-AzNetworkWatcherProtocolConfiguration
  href: ./New-AzNetworkWatcherProtocolConfiguration.yml
- text: Test-AzNetworkWatcherIPFlow
  href: ./Test-AzNetworkWatcherIPFlow.yml
- text: Test-AzNetworkWatcherConnectivity
  href: ./Test-AzNetworkWatcherConnectivity.yml
- text: Stop-AzNetworkWatcherConnectionMonitor
  href: ./Stop-AzNetworkWatcherConnectionMonitor.yml
- text: Set-AzNetworkWatcherConnectionMonitor
  href: ./Set-AzNetworkWatcherConnectionMonitor.yml
- text: Set-AzNetworkWatcherConfigFlowLog
  href: ./Set-AzNetworkWatcherConfigFlowLog.yml
- text: Remove-AzNetworkWatcherConnectionMonitor
  href: ./Remove-AzNetworkWatcherConnectionMonitor.yml
- text: New-AzNetworkWatcherConnectionMonitor
  href: ./New-AzNetworkWatcherConnectionMonitor.yml
- text: Get-AzNetworkWatcherTroubleshootingResult
  href: ./Get-AzNetworkWatcherTroubleshootingResult.yml
- text: Get-AzNetworkWatcherReachabilityReport
  href: ./Get-AzNetworkWatcherReachabilityReport.yml
- text: Get-AzNetworkWatcherReachabilityProvidersList
  href: ./Get-AzNetworkWatcherReachabilityProvidersList.yml
- text: Get-AzNetworkWatcherFlowLogStatus
  href: ./Get-AzNetworkWatcherFlowLogStatus.yml
- text: Get-AzNetworkWatcherConnectionMonitor
  href: ./Get-AzNetworkWatcherConnectionMonitor.yml
metadata:
  content_git_url: https://github.com/Azure/azure-powershell/blob/main/src/Network/Network/help/Invoke-AzNetworkWatcherNetworkConfigurationDiagnostic.md
  document type: cmdlet
  external help file: Microsoft.Azure.PowerShell.Cmdlets.Network.dll-Help.xml
  HelpUri: https://learn.microsoft.com/powershell/module/az.network/invoke-aznetworkwatchernetworkconfigurationdiagnostic
  Module Name: Az.Network
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/main/src/Network/Network/help/Invoke-AzNetworkWatcherNetworkConfigurationDiagnostic.md
  PlatyPS schema version: 2024-05-01
