### YamlMime:PowerShellCmdlet1
uid: Az.Nginx.Invoke-AzNginxAnalysisConfiguration
name: Invoke-AzNginxAnalysisConfiguration
module: Az.Nginx
isPreview: false
summary: |-
  Analyze an NGINX configuration without applying it to the NGINXaaS deployment
description: |-
  Analyze an NGINX configuration without applying it to the NGINXaaS deployment
parameters:
  cmdletParameters:
  - name: Body
    type: <xref href="Microsoft.Azure.PowerShell.Cmdlets.Nginx.Models.Api202401Preview.IAnalysisCreate" data-throw-if-not-resolved="False" />
    description: |-
      The request body for creating an analysis for an NGINX configuration.
      To construct, see NOTES section for BODY properties and create a hash table.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: Analysis
      position: Named
      isRequired: true
      valueFromPipeline: true
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    - name: AnalysisViaIdentity
      position: Named
      isRequired: true
      valueFromPipeline: true
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: ConfigFile
    type: <xref href="Microsoft.Azure.PowerShell.Cmdlets.Nginx.Models.Api202401Preview.INginxConfigurationFile" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
    description: |-
      .
      To construct, see NOTES section for CONFIGFILE properties and create a hash table.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: AnalysisExpanded
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    - name: AnalysisViaIdentityExpanded
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: ConfigProtectedFile
    type: <xref href="Microsoft.Azure.PowerShell.Cmdlets.Nginx.Models.Api202401Preview.INginxConfigurationFile" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
    description: |-
      .
      To construct, see NOTES section for CONFIGPROTECTEDFILE properties and create a hash table.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: AnalysisExpanded
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    - name: AnalysisViaIdentityExpanded
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: ConfigRootFile
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      The root file of the NGINX config file(s).
      It must match one of the files' filepath.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: AnalysisExpanded
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    - name: AnalysisViaIdentityExpanded
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: ConfigurationName
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      The name of configuration, only 'default' is supported value due to the singleton of NGINX conf
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: AnalysisExpanded
      position: Named
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    - name: Analysis
      position: Named
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: Confirm
    type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
    description: |-
      Prompts you for confirmation before running the cmdlet.
    aliases:
    - cf
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: DefaultProfile
    type: <xref href="System.Management.Automation.PSObject" data-throw-if-not-resolved="False" />
    description: |-
      The DefaultProfile parameter is not functional.
      Use the SubscriptionId parameter when available if executing the cmdlet against a different subscription.
    aliases:
    - AzureRMContext
    - AzureCredential
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: DeploymentName
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      The name of targeted NGINX deployment
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: AnalysisExpanded
      position: Named
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    - name: Analysis
      position: Named
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: InputObject
    type: <xref href="Microsoft.Azure.PowerShell.Cmdlets.Nginx.Models.INginxIdentity" data-throw-if-not-resolved="False" />
    description: |-
      Identity Parameter
      To construct, see NOTES section for INPUTOBJECT properties and create a hash table.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: AnalysisViaIdentityExpanded
      position: Named
      isRequired: true
      valueFromPipeline: true
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    - name: AnalysisViaIdentity
      position: Named
      isRequired: true
      valueFromPipeline: true
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: PackageData
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      .
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: AnalysisExpanded
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    - name: AnalysisViaIdentityExpanded
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: PackageProtectedFile
    type: <xref href="System.String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
    description: |-
      .
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: AnalysisExpanded
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    - name: AnalysisViaIdentityExpanded
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: ResourceGroupName
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      The name of the resource group.
      The name is case insensitive.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: AnalysisExpanded
      position: Named
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    - name: Analysis
      position: Named
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: SubscriptionId
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      The ID of the target subscription.
    defaultValue: (Get-AzContext).Subscription.Id
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: AnalysisExpanded
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    - name: Analysis
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: WhatIf
    type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
    description: |-
      Shows what would happen if the cmdlet runs.
      The cmdlet is not run.
    aliases:
    - wi
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  commonParameters: |-
    This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable,
    -InformationAction, -InformationVariable, -OutBuffer, -OutVariable, -PipelineVariable,
    -ProgressAction, -Verbose, -WarningAction, and -WarningVariable. For more information, see
    [about_CommonParameters](https://go.microsoft.com/fwlink/?LinkID=113216).
syntaxes:
- syntax: |-
    ```Syntax
    Invoke-AzNginxAnalysisConfiguration
        -ConfigurationName <String>
        -DeploymentName <String>
        -ResourceGroupName <String>
        [-SubscriptionId <String>]
        [-ConfigFile <INginxConfigurationFile[]>]
        [-ConfigProtectedFile <INginxConfigurationFile[]>]
        [-ConfigRootFile <String>]
        [-PackageData <String>]
        [-PackageProtectedFile <String[]>]
        [-DefaultProfile <PSObject>]
        [-WhatIf]
        [-Confirm]
        [<CommonParameters>]
    ```
  parameterSetName: AnalysisExpanded
  isDefault: true
- syntax: |-
    ```Syntax
    Invoke-AzNginxAnalysisConfiguration
        -ConfigurationName <String>
        -DeploymentName <String>
        -ResourceGroupName <String>
        -Body <IAnalysisCreate>
        [-SubscriptionId <String>]
        [-DefaultProfile <PSObject>]
        [-WhatIf]
        [-Confirm]
        [<CommonParameters>]
    ```
  parameterSetName: Analysis
  isDefault: false
- syntax: |-
    ```Syntax
    Invoke-AzNginxAnalysisConfiguration
        -InputObject <INginxIdentity>
        [-ConfigFile <INginxConfigurationFile[]>]
        [-ConfigProtectedFile <INginxConfigurationFile[]>]
        [-ConfigRootFile <String>]
        [-PackageData <String>]
        [-PackageProtectedFile <String[]>]
        [-DefaultProfile <PSObject>]
        [-WhatIf]
        [-Confirm]
        [<CommonParameters>]
    ```
  parameterSetName: AnalysisViaIdentityExpanded
  isDefault: false
- syntax: |-
    ```Syntax
    Invoke-AzNginxAnalysisConfiguration
        -InputObject <INginxIdentity>
        -Body <IAnalysisCreate>
        [-DefaultProfile <PSObject>]
        [-WhatIf]
        [-Confirm]
        [<CommonParameters>]
    ```
  parameterSetName: AnalysisViaIdentity
  isDefault: false
inputs:
- name: <xref href="Microsoft.Azure.PowerShell.Cmdlets.Nginx.Models.Api202401Preview.IAnalysisCreate" data-throw-if-not-resolved="False" />
- name: <xref href="Microsoft.Azure.PowerShell.Cmdlets.Nginx.Models.INginxIdentity" data-throw-if-not-resolved="False" />
outputs:
- name: <xref href="Microsoft.Azure.PowerShell.Cmdlets.Nginx.Models.Api202401Preview.IAnalysisResult" data-throw-if-not-resolved="False" />
examples:
- title: 'Example 1: Analyzing nginx configuration before creating the nginx configuration'
  description: |-
    ```powershell
    $confFile = New-AzNginxConfigurationFileObject -VirtualPath "nginx.conf" -Content 'xxxx'

    # configuration analysis
    $confAnalysis = Invoke-AzNginxAnalysisConfiguration -ConfigurationName default -DeploymentName xxxx -ResourceGroupName xxxx -ConfigFile $confFile -ConfigRootFile "nginx.conf"
    ```

    ```output
    Status
    ------
    SUCCEEDED
    ```

    This command analyzes the configuration before you submit to create your configuration for your nginx deployment
metadata:
  content_git_url: https://github.com/Azure/azure-powershell/blob/main/src/Nginx/Nginx/help/Invoke-AzNginxAnalysisConfiguration.md
  document type: cmdlet
  external help file: Az.Nginx-help.xml
  HelpUri: https://learn.microsoft.com/powershell/module/az.nginx/invoke-aznginxanalysisconfiguration
  Module Name: Az.Nginx
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/main/src/Nginx/Nginx/help/Invoke-AzNginxAnalysisConfiguration.md
  PlatyPS schema version: 2024-05-01
