### YamlMime:PowerShellCmdlet1
uid: Az.IotHub.Remove-AzIotHubConfiguration
name: Remove-AzIotHubConfiguration
module: Az.IotHub
isPreview: false
summary: |-
  Delete an IoT device configuration.
description: |-
  See https://learn.microsoft.com/azure/iot-hub/iot-hub-automatic-device-management for more information.
parameters:
  cmdletParameters:
  - name: Confirm
    type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
    description: |-
      Prompts you for confirmation before running the cmdlet.
    aliases:
    - cf
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: DefaultProfile
    type: <xref href="Microsoft.Azure.Commands.Common.Authentication.Abstractions.Core.IAzureContextContainer" data-throw-if-not-resolved="False" />
    description: |-
      The credentials, account, tenant, and subscription used for communication with Azure.
    aliases:
    - AzContext
    - AzureRmContext
    - AzureCredential
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: InputObject
    type: <xref href="Microsoft.Azure.Commands.Management.IotHub.Models.PSIotHub" data-throw-if-not-resolved="False" />
    description: |-
      IotHub object
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: InputObjectSet
      position: "0"
      isRequired: true
      valueFromPipeline: true
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: IotHubName
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      Name of the Iot Hub
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: ResourceSet
      position: "1"
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: Name
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      Identifier for the configuration.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: PassThru
    type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
    description: |-
      Allows to return the boolean object.
      By default, this cmdlet does not generate any output.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: ResourceGroupName
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      Name of the Resource Group
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: ResourceSet
      position: "0"
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: ResourceId
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      IotHub Resource Id
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: ResourceIdSet
      position: "0"
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: true
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: WhatIf
    type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
    description: |-
      Shows what would happen if the cmdlet runs.
      The cmdlet is not run.
    aliases:
    - wi
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  commonParameters: |-
    This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable,
    -InformationAction, -InformationVariable, -OutBuffer, -OutVariable, -PipelineVariable,
    -ProgressAction, -Verbose, -WarningAction, and -WarningVariable. For more information, see
    [about_CommonParameters](https://go.microsoft.com/fwlink/?LinkID=113216).
syntaxes:
- syntax: |-
    ```Syntax
    Remove-AzIotHubConfiguration
        [-ResourceGroupName] <String>
        [-IotHubName] <String>
        [-Name <String>]
        [-PassThru]
        [-DefaultProfile <IAzureContextContainer>]
        [-WhatIf]
        [-Confirm]
        [<CommonParameters>]
    ```
  parameterSetName: ResourceSet
  isDefault: true
- syntax: |-
    ```Syntax
    Remove-AzIotHubConfiguration
        [-InputObject] <PSIotHub>
        [-Name <String>]
        [-PassThru]
        [-DefaultProfile <IAzureContextContainer>]
        [-WhatIf]
        [-Confirm]
        [<CommonParameters>]
    ```
  parameterSetName: InputObjectSet
  isDefault: false
- syntax: |-
    ```Syntax
    Remove-AzIotHubConfiguration
        [-ResourceId] <String>
        [-Name <String>]
        [-PassThru]
        [-DefaultProfile <IAzureContextContainer>]
        [-WhatIf]
        [-Confirm]
        [<CommonParameters>]
    ```
  parameterSetName: ResourceIdSet
  isDefault: false
inputs:
- name: <xref href="Microsoft.Azure.Commands.Management.IotHub.Models.PSIotHub" data-throw-if-not-resolved="False" />
- name: <xref href="System.String" data-throw-if-not-resolved="False" />
outputs:
- name: <xref href="System.Boolean" data-throw-if-not-resolved="False" />
examples:
- title: Example 1
  description: |-
    ```powershell
    Remove-AzIotHubConfiguration -ResourceGroupName "myresourcegroup" -IotHubName "myiothub" -Name "config1"
    ```

    Delete an IoT device configuration.
metadata:
  content_git_url: https://github.com/Azure/azure-powershell/blob/main/src/IotHub/IotHub/help/Remove-AzIotHubConfiguration.md
  document type: cmdlet
  external help file: Microsoft.Azure.PowerShell.Cmdlets.IotHub.dll-Help.xml
  HelpUri: https://learn.microsoft.com/powershell/module/az.iothub/remove-aziothubconfiguration
  Module Name: Az.IotHub
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/main/src/IotHub/IotHub/help/Remove-AzIotHubConfiguration.md
  PlatyPS schema version: 2024-05-01
