blank_issues_enabled: true
contact_links:
  - name: 🎃 Hacktoberfest 2022
    url: https://github.com/MicrosoftDocs/PowerShell-Docs/issues/9257
    about: >-
      If you'd like to participate in Hacktoberfest 2022, before filing an issue, check the info
      and instructions.
  # - name: PowerShell Product Feedback
  #   url: https://github.com/PowerShell/PowerShell/issues/new/choose
  #   about: Please open feature requests for current PowerShell here.
  # - name: Support
  #   url: https://learn.microsoft.com/powershell/scripting/community/community-support
  #   about: PowerShell Support Questions/Help
