### YamlMime:PowerShellCmdlet1
uid: Az.Maintenance.Get-AzMaintenanceConfiguration
name: Get-AzMaintenanceConfiguration
module: Az.Maintenance
isPreview: false
summary: |-
  Get Maintenance configuration record
description: |-
  Get Maintenance configuration record
parameters:
  cmdletParameters:
  - name: DefaultProfile
    type: <xref href="Microsoft.Azure.Commands.Common.Authentication.Abstractions.Core.IAzureContextContainer" data-throw-if-not-resolved="False" />
    description: |-
      The credentials, account, tenant, and subscription used for communication with Azure.
    aliases:
    - AzContext
    - AzureRmContext
    - AzureCredential
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: Name
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      The maintenance configuration Name.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: "1"
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: true
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: ResourceGroupName
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      The resource Group Name.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: "0"
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: true
      valueFromRemainingArguments: false
    supportsWildcards: false
  commonParameters: |-
    This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable,
    -InformationAction, -InformationVariable, -OutBuffer, -OutVariable, -PipelineVariable,
    -ProgressAction, -Verbose, -WarningAction, and -WarningVariable. For more information, see
    [about_CommonParameters](https://go.microsoft.com/fwlink/?LinkID=113216).
syntaxes:
- syntax: |-
    ```Syntax
    Get-AzMaintenanceConfiguration
        [[-ResourceGroupName] <String>]
        [[-Name] <String>]
        [-DefaultProfile <IAzureContextContainer>]
        [<CommonParameters>]
    ```
  parameterSetName: Default
  isDefault: true
inputs:
- name: <xref href="System.String" data-throw-if-not-resolved="False" />
outputs:
- name: <xref href="Microsoft.Azure.Commands.Maintenance.Models.PSMaintenanceConfiguration" data-throw-if-not-resolved="False" />
examples:
- title: Example 1
  description: |-
    ```powershell
    Get-AzMaintenanceConfiguration -ResourceGroupName smdtest -Name workervmscentralus
    ```

    ```output
    Location            : centralus
    Tags                : {}
    NamespaceProperty   :
    ExtensionProperties : {}
    MaintenanceScope    : Host
    Id                  : /subscriptions/42c974dd-2c03-4f1b-96ad-b07f050aaa74/resourcegroups/smdtest/providers/Microsoft.Maintenance/maintenanceConfigurations/workervmscentralus
    Name                : workervmscentralus
    Type                : Microsoft.Maintenance/maintenanceConfigurations
    ```

    Get Maintenance configuration record
metadata:
  content_git_url: https://github.com/Azure/azure-powershell/blob/main/src/Maintenance/Maintenance/help/Get-AzMaintenanceConfiguration.md
  document type: cmdlet
  external help file: Microsoft.Azure.PowerShell.Cmdlets.Maintenance.dll-Help.xml
  HelpUri: https://learn.microsoft.com/powershell/module/az.maintenance/get-azmaintenanceconfiguration
  Module Name: Az.Maintenance
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/main/src/Maintenance/Maintenance/help/Get-AzMaintenanceConfiguration.md
  PlatyPS schema version: 2024-05-01
