### YamlMime:PowerShellCmdlet1
uid: Az.MachineLearningServices.Remove-AzMLWorkspaceEnvironmentContainer
name: Remove-AzMLWorkspaceEnvironmentContainer
module: Az.MachineLearningServices
isPreview: false
summary: |-
  Delete container.
description: |-
  Delete container.
parameters:
  cmdletParameters:
  - name: Confirm
    type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
    description: |-
      Prompts you for confirmation before running the cmdlet.
    aliases:
    - cf
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: DefaultProfile
    type: <xref href="System.Management.Automation.PSObject" data-throw-if-not-resolved="False" />
    description: |-
      The DefaultProfile parameter is not functional.
      Use the SubscriptionId parameter when available if executing the cmdlet against a different subscription.
    aliases:
    - AzureRMContext
    - AzureCredential
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: InputObject
    type: <xref href="Microsoft.Azure.PowerShell.Cmdlets.MachineLearningServices.Models.IMachineLearningServicesIdentity" data-throw-if-not-resolved="False" />
    description: |-
      Identity Parameter
      To construct, see NOTES section for INPUTOBJECT properties and create a hash table.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: DeleteViaIdentity
      position: Named
      isRequired: true
      valueFromPipeline: true
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: Name
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      Container name.
      This is case-sensitive.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: Delete
      position: Named
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: PassThru
    type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
    description: |-
      Returns true when the command succeeds
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: ResourceGroupName
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      The name of the resource group.
      The name is case insensitive.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: Delete
      position: Named
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: SubscriptionId
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      The ID of the target subscription.
    defaultValue: (Get-AzContext).Subscription.Id
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: Delete
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: WhatIf
    type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
    description: |-
      Shows what would happen if the cmdlet runs.
      The cmdlet is not run.
    aliases:
    - wi
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: WorkspaceName
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      Name of Azure Machine Learning workspace.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: Delete
      position: Named
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  commonParameters: |-
    This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable,
    -InformationAction, -InformationVariable, -OutBuffer, -OutVariable, -PipelineVariable,
    -ProgressAction, -Verbose, -WarningAction, and -WarningVariable. For more information, see
    [about_CommonParameters](https://go.microsoft.com/fwlink/?LinkID=113216).
syntaxes:
- syntax: |-
    ```Syntax
    Remove-AzMLWorkspaceEnvironmentContainer
        -Name <String>
        -ResourceGroupName <String>
        -WorkspaceName <String>
        [-SubscriptionId <String>]
        [-DefaultProfile <PSObject>]
        [-PassThru]
        [-WhatIf]
        [-Confirm]
        [<CommonParameters>]
    ```
  parameterSetName: Delete
  isDefault: true
- syntax: |-
    ```Syntax
    Remove-AzMLWorkspaceEnvironmentContainer
        -InputObject <IMachineLearningServicesIdentity>
        [-DefaultProfile <PSObject>]
        [-PassThru]
        [-WhatIf]
        [-Confirm]
        [<CommonParameters>]
    ```
  parameterSetName: DeleteViaIdentity
  isDefault: false
inputs:
- name: <xref href="Microsoft.Azure.PowerShell.Cmdlets.MachineLearningServices.Models.IMachineLearningServicesIdentity" data-throw-if-not-resolved="False" />
outputs:
- name: <xref href="System.Boolean" data-throw-if-not-resolved="False" />
examples:
- title: 'Example 1: Delete environment container'
  description: |-
    ```powershell
    Remove-AzMLWorkspaceEnvironmentContainer  -ResourceGroupName ml-rg-test -WorkspaceName mlworkspace-portal01 -Name pwshenv01
    ```

    Delete environment container
- title: 'Example 2: Delete environment container by pipeline'
  description: |-
    ```powershell
    Get-AzMLWorkspaceEnvironmentContainer  -ResourceGroupName ml-rg-test -WorkspaceName mlworkspace-portal01 -Name pwshenv01 | Remove-AzMLWorkspaceEnvironmentContainer
    ```

    Delete environment container by pipeline
metadata:
  content_git_url: https://github.com/Azure/azure-powershell/blob/main/src/MachineLearningServices/MachineLearningServices/help/Remove-AzMLWorkspaceEnvironmentContainer.md
  document type: cmdlet
  external help file: Az.MachineLearningServices-help.xml
  HelpUri: https://learn.microsoft.com/powershell/module/az.machinelearningservices/remove-azmlworkspaceenvironmentcontainer
  Module Name: Az.MachineLearningServices
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/main/src/MachineLearningServices/MachineLearningServices/help/Remove-AzMLWorkspaceEnvironmentContainer.md
  PlatyPS schema version: 2024-05-01
