### YamlMime:PowerShellCmdlet1
uid: Az.Compute.Add-AzVmGalleryApplication
name: Add-AzVmGalleryApplication
module: Az.Compute
isPreview: false
summary: |-
  Add a GalleryApplication object to the PSVirtualMachine object.
description: |-
  Adds a GalleryApplication object to the PSVirtualMachine object.
parameters:
  cmdletParameters:
  - name: Confirm
    type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
    description: |-
      Prompts you for confirmation before running the cmdlet.
    aliases:
    - cf
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: DefaultProfile
    type: <xref href="Microsoft.Azure.Commands.Common.Authentication.Abstractions.Core.IAzureContextContainer" data-throw-if-not-resolved="False" />
    description: |-
      The credentials, account, tenant, and subscription used for communication with Azure.
    aliases:
    - AzContext
    - AzureRmContext
    - AzureCredential
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: GalleryApplication
    type: <xref href="Microsoft.Azure.Commands.Compute.Automation.Models.PSVMGalleryApplication" data-throw-if-not-resolved="False" />
    description: |-
      PSVMGalleryApplication Object.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: Order
    type: <xref href="System.Int32" data-throw-if-not-resolved="False" />
    description: |-
      Order in which the application will be install in.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: TreatFailureAsDeploymentFailure
    type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
    description: |-
      If true, any failure for any operation in the VmApplication will fail the deployment. Defaults to false if not specified.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: true
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: VM
    type: <xref href="Microsoft.Azure.Commands.Compute.Models.PSVirtualMachine" data-throw-if-not-resolved="False" />
    description: |-
      The PSVirtualMachine object to add a Gallery Application Reference ID.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: WhatIf
    type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
    description: |-
      Shows what would happen if the cmdlet runs. The cmdlet is not run.
    aliases:
    - wi
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  commonParameters: |-
    This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable,
    -InformationAction, -InformationVariable, -OutBuffer, -OutVariable, -PipelineVariable,
    -ProgressAction, -Verbose, -WarningAction, and -WarningVariable. For more information, see
    [about_CommonParameters](https://go.microsoft.com/fwlink/?LinkID=113216).
syntaxes:
- syntax: |-
    ```Syntax
    Add-AzVmGalleryApplication
        -VM <PSVirtualMachine>
        -GalleryApplication <PSVMGalleryApplication>
        [-Order <Int32>]
        [-TreatFailureAsDeploymentFailure]
        [-DefaultProfile <IAzureContextContainer>]
        [-WhatIf]
        [-Confirm]
        [<CommonParameters>]
    ```
  parameterSetName: Default
  isDefault: true
inputs:
- name: <xref href="None" data-throw-if-not-resolved="False" />
outputs:
- name: <xref href="Microsoft.Azure.Commands.Compute.Models.PSVirtualMachine" data-throw-if-not-resolved="False" />
examples:
- title: Example 1
  description: |-
    ```powershell
    $vm = Get-AzVM -ResourceGroupName $rgName -Name $vmName
    $vmGal = New-AzVmGalleryApplication -PackageReferenceId $packageRefId -ConfigReferenceId $configRefId
    Add-AzVmGalleryApplication -VM $vm -GalleryApplication $vmGal -Order 1
    ```

    This example creates a local VMGalleryApplication object and adds it to a PSVirtualMachine object.
metadata:
  content_git_url: https://github.com/Azure/azure-powershell/blob/main/src/Compute/Compute/help/Add-AzVmGalleryApplication.md
  document type: cmdlet
  external help file: Microsoft.Azure.PowerShell.Cmdlets.Compute.dll-Help.xml
  HelpUri: https://learn.microsoft.com/powershell/module/az.compute/add-azvmgalleryapplication
  Module Name: Az.Compute
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/main/src/Compute/Compute/help/Add-AzVmGalleryApplication.md
  PlatyPS schema version: 2024-05-01
