### YamlMime:PowerShellCmdlet1
uid: Az.Compute.New-AzVmssVaultCertificateConfig
name: New-AzVmssVaultCertificateConfig
module: Az.Compute
isPreview: false
summary: |-
  Creates a Key Vault certificate configuration.
description: |-
  The **New-AzVmssVaultCertificateConfig** cmdlet specifies the secret that needs to be placed on the Virtual Machine Scale Set (VMSS) virtual machines.
  The output of this cmdlet is intended to be used with the Add-AzVmssSecret cmdlet.
parameters:
  cmdletParameters:
  - name: CertificateStore
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      Specifies the certificate store on the virtual machines in the scale set where the certificate is added.
      This is only valid for Windows Virtual Machine Scale Sets.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: "1"
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: true
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: CertificateUrl
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      Specifies the URI of a certificate stored in the Key Vault.
      It is the base64 encoding of the following JSON Object which is encoded in UTF-8:
      {
        "data":"\<Base64-encoded-certificate\>",
        "dataType":"pfx",
        "password":"\<pfx-file-password\>"
      }
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: "0"
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: true
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: Confirm
    type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
    description: |-
      Prompts you for confirmation before running the cmdlet.
    aliases:
    - cf
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: DefaultProfile
    type: <xref href="Microsoft.Azure.Commands.Common.Authentication.Abstractions.Core.IAzureContextContainer" data-throw-if-not-resolved="False" />
    description: |-
      The credentials, account, tenant, and subscription used for communication with azure.
    aliases:
    - AzContext
    - AzureRmContext
    - AzureCredential
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: WhatIf
    type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
    description: |-
      Shows what would happen if the cmdlet runs. The cmdlet is not run.
    aliases:
    - wi
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  commonParameters: |-
    This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable,
    -InformationAction, -InformationVariable, -OutBuffer, -OutVariable, -PipelineVariable,
    -ProgressAction, -Verbose, -WarningAction, and -WarningVariable. For more information, see
    [about_CommonParameters](https://go.microsoft.com/fwlink/?LinkID=113216).
syntaxes:
- syntax: |-
    ```Syntax
    New-AzVmssVaultCertificateConfig
        [[-CertificateUrl] <String>]
        [[-CertificateStore] <String>]
        [-DefaultProfile <IAzureContextContainer>]
        [-WhatIf]
        [-Confirm]
        [<CommonParameters>]
    ```
  parameterSetName: Default
  isDefault: true
inputs:
- name: <xref href="System.String" data-throw-if-not-resolved="False" />
outputs:
- name: <xref href="Microsoft.Azure.Management.Compute.Models.VaultCertificate" data-throw-if-not-resolved="False" />
examples:
- title: 'Example 1: Create a Key Vault certificate configuration'
  description: |-
    ```powershell
    New-AzVmssVaultCertificateConfig -CertificateUrl "http://keyVaultName.vault.contoso.net/secrets/secretName/secretVersion" -CertificateStore "MyCerts"
    ```

    This command creates a Key Vault certificate configuration that uses the certificate store named MyCerts located at the specified certificate URL.
links:
- text: Add-AzVmssSecret
  href: ./Add-AzVmssSecret.yml
metadata:
  content_git_url: https://github.com/Azure/azure-powershell/blob/main/src/Compute/Compute/help/New-AzVmssVaultCertificateConfig.md
  document type: cmdlet
  external help file: Microsoft.Azure.PowerShell.Cmdlets.Compute.dll-Help.xml
  HelpUri: https://learn.microsoft.com/powershell/module/az.compute/new-azvmssvaultcertificateconfig
  Module Name: Az.Compute
  ms.assetid: 5CC89899-00B6-424A-8896-FD32DE9DDA28
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/main/src/Compute/Compute/help/New-AzVmssVaultCertificateConfig.md
  PlatyPS schema version: 2024-05-01
