### YamlMime:PowerShellCmdlet1
uid: Az.Compute.Remove-AzGalleryApplicationVersion
name: Remove-AzGalleryApplicationVersion
module: Az.Compute
isPreview: false
summary: |-
  Delete a gallery Application Version.
description: |-
  Delete a gallery Application Version.
parameters:
  cmdletParameters:
  - name: AsJob
    type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
    description: |-
      Run the command as a job
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: Confirm
    type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
    description: |-
      Prompts you for confirmation before running the cmdlet.
    aliases:
    - cf
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: DefaultProfile
    type: <xref href="System.Management.Automation.PSObject" data-throw-if-not-resolved="False" />
    description: |-
      The DefaultProfile parameter is not functional.
      Use the SubscriptionId parameter when available if executing the cmdlet against a different subscription.
    aliases:
    - AzureRMContext
    - AzureCredential
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: GalleryApplicationName
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      The name of the gallery Application Definition in which the Application Version resides.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: Delete
      position: Named
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: GalleryName
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      The name of the Shared Application Gallery in which the Application Definition resides.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: Delete
      position: Named
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: InputObject
    type: <xref href="Microsoft.Azure.PowerShell.Cmdlets.Compute.Models.IComputeIdentity" data-throw-if-not-resolved="False" />
    description: |-
      Identity Parameter
      To construct, see NOTES section for INPUTOBJECT properties and create a hash table.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: DeleteViaIdentity
      position: Named
      isRequired: true
      valueFromPipeline: true
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: Name
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      The name of the gallery Application Version to be deleted.
    aliases:
    - GalleryApplicationVersionName
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: Delete
      position: Named
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: NoWait
    type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
    description: |-
      Run the command asynchronously
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: PassThru
    type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
    description: |-
      Returns true when the command succeeds
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: ResourceGroupName
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      The name of the resource group.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: Delete
      position: Named
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: SubscriptionId
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      Subscription credentials which uniquely identify Microsoft Azure subscription.
      The subscription ID forms part of the URI for every service call.
    defaultValue: (Get-AzContext).Subscription.Id
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: Delete
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: WhatIf
    type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
    description: |-
      Shows what would happen if the cmdlet runs.
      The cmdlet is not run.
    aliases:
    - wi
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  commonParameters: |-
    This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable,
    -InformationAction, -InformationVariable, -OutBuffer, -OutVariable, -PipelineVariable,
    -ProgressAction, -Verbose, -WarningAction, and -WarningVariable. For more information, see
    [about_CommonParameters](https://go.microsoft.com/fwlink/?LinkID=113216).
syntaxes:
- syntax: |-
    ```Syntax
    Remove-AzGalleryApplicationVersion
        -GalleryApplicationName <String>
        -GalleryName <String>
        -Name <String>
        -ResourceGroupName <String>
        [-SubscriptionId <String>]
        [-DefaultProfile <PSObject>]
        [-AsJob]
        [-NoWait]
        [-PassThru]
        [-WhatIf]
        [-Confirm]
        [<CommonParameters>]
    ```
  parameterSetName: Delete
  isDefault: true
- syntax: |-
    ```Syntax
    Remove-AzGalleryApplicationVersion
        -InputObject <IComputeIdentity>
        [-DefaultProfile <PSObject>]
        [-AsJob]
        [-NoWait]
        [-PassThru]
        [-WhatIf]
        [-Confirm]
        [<CommonParameters>]
    ```
  parameterSetName: DeleteViaIdentity
  isDefault: false
inputs:
- name: <xref href="Microsoft.Azure.PowerShell.Cmdlets.Compute.Models.IComputeIdentity" data-throw-if-not-resolved="False" />
outputs:
- name: <xref href="System.Boolean" data-throw-if-not-resolved="False" />
examples:
- title: 'Example 1: Remove a Gallery Application Version'
  description: |-
    ```powershell
    Remove-AzGalleryApplicationVersion -ResourceGroupName $rgName -GalleryName $galleryName -GalleryApplicationName $galleryApplicationName -Name $name
    ```

    Delete a gallery application version.
metadata:
  content_git_url: https://github.com/Azure/azure-powershell/blob/main/src/Compute/Compute/help/Remove-AzGalleryApplicationVersion.md
  document type: cmdlet
  external help file: Az.Compute-help.xml
  HelpUri: https://learn.microsoft.com/powershell/module/az.compute/remove-azgalleryapplicationversion
  Module Name: Az.Compute
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/main/src/Compute/Compute/help/Remove-AzGalleryApplicationVersion.md
  PlatyPS schema version: 2024-05-01
