### YamlMime:PowerShellCmdlet1
uid: Az.HDInsight.New-AzHDInsightIPConfiguration
name: New-AzHDInsightIPConfiguration
module: Az.HDInsight
isPreview: false
summary: |-
  Creates the IP configuration of private link configuration.
description: |-
  This cmdlet **New-AzHDInsightIPConfiguration** creates the ip configuration in memory.
parameters:
  cmdletParameters:
  - name: DefaultProfile
    type: <xref href="Microsoft.Azure.Commands.Common.Authentication.Abstractions.Core.IAzureContextContainer" data-throw-if-not-resolved="False" />
    description: |-
      The credentials, account, tenant, and subscription used for communication with Azure.
    aliases:
    - AzContext
    - AzureRmContext
    - AzureCredential
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: Name
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      Gets or sets the ip configuration name.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: Primary
    type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
    description: |-
      Gets or sets the flag indicates whether this IP configuration is primary for the corresponding NIC.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: PrivateIPAddress
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      Gets or sets the private ip address.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: PrivateIPAllocationMethod
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      Gets or sets the private ip allocation method.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: SubnetId
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      Gets or sets the subnet resource id.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  commonParameters: |-
    This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable,
    -InformationAction, -InformationVariable, -OutBuffer, -OutVariable, -PipelineVariable,
    -ProgressAction, -Verbose, -WarningAction, and -WarningVariable. For more information, see
    [about_CommonParameters](https://go.microsoft.com/fwlink/?LinkID=113216).
syntaxes:
- syntax: |-
    ```Syntax
    New-AzHDInsightIPConfiguration
        [-Name <String>]
        [-Primary]
        [-PrivateIPAddress <String>]
        [-PrivateIPAllocationMethod <String>]
        [-SubnetId <String>]
        [-DefaultProfile <IAzureContextContainer>]
        [<CommonParameters>]
    ```
  parameterSetName: Default
  isDefault: true
inputs:
- name: <xref href="None" data-throw-if-not-resolved="False" />
outputs:
- name: <xref href="Microsoft.Azure.Commands.HDInsight.Models.AzureHDInsightIPConfiguration" data-throw-if-not-resolved="False" />
examples:
- title: Example 1
  description: |-
    ```powershell
    $vnetId="/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/testrg/providers/Microsoft.Network/virtualNetworks/testvnet"
    $subnetName="default"
    $ipConfigName="ipconfig"
    $privateIPAllocationMethod="dynamic"
    $subnetId=$vnetId+"/subnets/"+$subnetName
    # Create Private IP configuration
    $ipConfiguration= New-AzHDInsightIPConfiguration -Name $ipConfigName -PrivateIPAllocationMethod $privateIPAllocationMethod -SubnetId $subnetId -Primary
    ```

    This creates the ip configuration object in memory.
metadata:
  content_git_url: https://github.com/Azure/azure-powershell/blob/main/src/HDInsight/HDInsight/help/New-AzHDInsightIPConfiguration.md
  document type: cmdlet
  external help file: Microsoft.Azure.PowerShell.Cmdlets.HDInsight.dll-Help.xml
  HelpUri: https://learn.microsoft.com/powershell/module/az.hdinsight/new-azhdinsightipconfiguration
  Module Name: Az.HDInsight
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/main/src/HDInsight/HDInsight/help/New-AzHDInsightIPConfiguration.md
  PlatyPS schema version: 2024-05-01
