### YamlMime:PowerShellCmdlet1
uid: Az.HDInsight.New-AzHDInsightClusterAutoscaleConfiguration
name: New-AzHDInsightClusterAutoscaleConfiguration
module: Az.HDInsight
isPreview: false
summary: |-
  Creates a non-persisted object that describes the autoscale configuration of an Azure HDInsight cluster.
description: |-
  The cmdlet **New-AzHDInsightClusterAutoscaleConfiguration** creates a non-persisted object that describes the autoscale configuration of an Azure HDInsight cluster.
parameters:
  cmdletParameters:
  - name: Condition
    type: <xref href="System.Collections.Generic.List`1" data-throw-if-not-resolved="False" /><span>[</span><xref href="Microsoft.Azure.Commands.HDInsight.Models.AzureHDInsightAutoscaleCondition" data-throw-if-not-resolved="False" /><span>]</span>
    description: |-
      Gets or sets the condition of schedule-based autoscale.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: ScheduleAutoscaleParameterSet
      position: Named
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: DefaultProfile
    type: <xref href="Microsoft.Azure.Commands.Common.Authentication.Abstractions.Core.IAzureContextContainer" data-throw-if-not-resolved="False" />
    description: |-
      The credentials, account, tenant, and subscription used for communication with Azure.
    aliases:
    - AzContext
    - AzureRmContext
    - AzureCredential
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: MaxWorkerNodeCount
    type: <xref href="System.Int32" data-throw-if-not-resolved="False" />
    description: |-
      Gets or sets the maximal workernode count of load-based autoscale.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: LoadAutoscaleParameterSet
      position: Named
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: MinWorkerNodeCount
    type: <xref href="System.Int32" data-throw-if-not-resolved="False" />
    description: |-
      Gets or sets the minimal workernode count of load-based autoscale.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: LoadAutoscaleParameterSet
      position: Named
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: TimeZone
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      Gets or sets the time zone of schedule-based autoscale.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: ScheduleAutoscaleParameterSet
      position: Named
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  commonParameters: |-
    This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable,
    -InformationAction, -InformationVariable, -OutBuffer, -OutVariable, -PipelineVariable,
    -ProgressAction, -Verbose, -WarningAction, and -WarningVariable. For more information, see
    [about_CommonParameters](https://go.microsoft.com/fwlink/?LinkID=113216).
syntaxes:
- syntax: |-
    ```Syntax
    New-AzHDInsightClusterAutoscaleConfiguration
        -MinWorkerNodeCount <Int32>
        -MaxWorkerNodeCount <Int32>
        [-DefaultProfile <IAzureContextContainer>]
        [<CommonParameters>]
    ```
  parameterSetName: LoadAutoscaleParameterSet
  isDefault: true
- syntax: |-
    ```Syntax
    New-AzHDInsightClusterAutoscaleConfiguration
        -TimeZone <String>
        -Condition <System.Collections.Generic.List`1[Microsoft.Azure.Commands.HDInsight.Models.AzureHDInsightAutoscaleCondition]>
        [-DefaultProfile <IAzureContextContainer>]
        [<CommonParameters>]
    ```
  parameterSetName: ScheduleAutoscaleParameterSet
  isDefault: false
inputs:
- name: <xref href="None" data-throw-if-not-resolved="False" />
outputs:
- name: <xref href="Microsoft.Azure.Commands.HDInsight.Models.AzureHDInsightAutoscale" data-throw-if-not-resolved="False" />
examples:
- title: 'Example 1: Create an object which describes Load-based autoscale configuration'
  description: |-
    ```powershell
    New-AzHDInsightClusterAutoscaleConfiguration -MinWorkerNodeCount 3 -MaxWorkerNodeCount 5
    ```

    This command creates an object which describes Load-based autoscale configuration.
- title: 'Example 2: Create an object which describes Schedule-based autoscale configuration'
  description: |-
    ```powershell
    # Create an autoscale condition firstly
    $condition=New-AzHDInsightClusterAutoscaleScheduleCondition -Day Monday -Time 09:00 -WorkerNodeCount 5
    New-AzHDInsightClusterAutoscaleConfiguration -TimeZone ([System.TimeZoneInfo]::Local).Id `
            -Condition $condition
    ```

    This command creates an object which describes Schedule-based autoscale configuration.
links:
- text: Set-AzHDInsightClusterAutoscaleConfiguration
  href: ./Set-AzHDInsightClusterAutoscaleConfiguration.yml
- text: Get-AzHDInsightClusterAutoscaleConfiguration
  href: ./Get-AzHDInsightClusterAutoscaleConfiguration.yml
- text: Remove-AzHDInsightClusterAutoscaleConfiguration
  href: ./Remove-AzHDInsightClusterAutoscaleConfiguration.yml
metadata:
  content_git_url: https://github.com/Azure/azure-powershell/blob/main/src/HDInsight/HDInsight/help/New-AzHDInsightClusterAutoscaleConfiguration.md
  document type: cmdlet
  external help file: Microsoft.Azure.PowerShell.Cmdlets.HDInsight.dll-Help.xml
  HelpUri: https://learn.microsoft.com/powershell/module/az.hdinsight/new-azhdinsightclusterautoscaleconfiguration
  Module Name: Az.HDInsight
  ms.assetid: 86276DF3-95E2-405F-BA46-F188B7AE3B9B
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/main/src/HDInsight/HDInsight/help/New-AzHDInsightClusterAutoscaleConfiguration.md
  PlatyPS schema version: 2024-05-01
