### YamlMime:PowerShellCmdlet1
uid: Az.ServiceBus.New-AzServiceBusGeoDRConfiguration
name: New-AzServiceBusGeoDRConfiguration
module: Az.ServiceBus
isPreview: false
summary: |-
  create a new Alias(Disaster Recovery configuration)
description: |-
  create a new Alias(Disaster Recovery configuration)
parameters:
  cmdletParameters:
  - name: AlternateName
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      Primary/Secondary eventhub namespace name, which is part of GEO DR pairing
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: CreateExpanded
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    - name: CreateViaIdentityNamespaceExpanded
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: Confirm
    type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
    description: |-
      Prompts you for confirmation before running the cmdlet.
    aliases:
    - cf
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: DefaultProfile
    type: <xref href="System.Management.Automation.PSObject" data-throw-if-not-resolved="False" />
    description: |-
      The DefaultProfile parameter is not functional.
      Use the SubscriptionId parameter when available if executing the cmdlet against a different subscription.
    aliases:
    - AzureRMContext
    - AzureCredential
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: Name
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      The Disaster Recovery configuration name
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: NamespaceInputObject
    type: <xref href="Microsoft.Azure.PowerShell.Cmdlets.ServiceBus.Models.IServiceBusIdentity" data-throw-if-not-resolved="False" />
    description: |-
      Identity Parameter
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: CreateViaIdentityNamespaceExpanded
      position: Named
      isRequired: true
      valueFromPipeline: true
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    - name: CreateViaIdentityNamespace
      position: Named
      isRequired: true
      valueFromPipeline: true
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: NamespaceName
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      The namespace name
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: CreateExpanded
      position: Named
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: Parameter
    type: <xref href="Microsoft.Azure.PowerShell.Cmdlets.ServiceBus.Models.IArmDisasterRecovery" data-throw-if-not-resolved="False" />
    description: |-
      Single item in List or Get Alias(Disaster Recovery configuration) operation
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: CreateViaIdentityNamespace
      position: Named
      isRequired: true
      valueFromPipeline: true
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: PartnerNamespace
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      ARM Id of the Primary/Secondary eventhub namespace name, which is part of GEO DR pairing
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: CreateExpanded
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    - name: CreateViaIdentityNamespaceExpanded
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: PassThru
    type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
    description: |-
      Returns true when the command succeeds
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: ResourceGroupName
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      Name of the Resource group within the Azure subscription.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: CreateExpanded
      position: Named
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: SubscriptionId
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      Subscription credentials that uniquely identify a Microsoft Azure subscription.
      The subscription ID forms part of the URI for every service call.
    defaultValue: (Get-AzContext).Subscription.Id
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: CreateExpanded
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: WhatIf
    type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
    description: |-
      Shows what would happen if the cmdlet runs.
      The cmdlet is not run.
    aliases:
    - wi
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  commonParameters: |-
    This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable,
    -InformationAction, -InformationVariable, -OutBuffer, -OutVariable, -PipelineVariable,
    -ProgressAction, -Verbose, -WarningAction, and -WarningVariable. For more information, see
    [about_CommonParameters](https://go.microsoft.com/fwlink/?LinkID=113216).
syntaxes:
- syntax: |-
    ```Syntax
    New-AzServiceBusGeoDRConfiguration
        -Name <String>
        -NamespaceName <String>
        -ResourceGroupName <String>
        [-SubscriptionId <String>]
        [-AlternateName <String>]
        [-PartnerNamespace <String>]
        [-DefaultProfile <PSObject>]
        [-PassThru]
        [-WhatIf]
        [-Confirm]
        [<CommonParameters>]
    ```
  parameterSetName: CreateExpanded
  isDefault: true
- syntax: |-
    ```Syntax
    New-AzServiceBusGeoDRConfiguration
        -Name <String>
        -NamespaceInputObject <IServiceBusIdentity>
        [-AlternateName <String>]
        [-PartnerNamespace <String>]
        [-DefaultProfile <PSObject>]
        [-PassThru]
        [-WhatIf]
        [-Confirm]
        [<CommonParameters>]
    ```
  parameterSetName: CreateViaIdentityNamespaceExpanded
  isDefault: false
- syntax: |-
    ```Syntax
    New-AzServiceBusGeoDRConfiguration
        -Name <String>
        -NamespaceInputObject <IServiceBusIdentity>
        -Parameter <IArmDisasterRecovery>
        [-DefaultProfile <PSObject>]
        [-PassThru]
        [-WhatIf]
        [-Confirm]
        [<CommonParameters>]
    ```
  parameterSetName: CreateViaIdentityNamespace
  isDefault: false
inputs:
- name: <xref href="Microsoft.Azure.PowerShell.Cmdlets.ServiceBus.Models.IArmDisasterRecovery" data-throw-if-not-resolved="False" />
- name: <xref href="Microsoft.Azure.PowerShell.Cmdlets.ServiceBus.Models.IServiceBusIdentity" data-throw-if-not-resolved="False" />
outputs:
- name: <xref href="Microsoft.Azure.PowerShell.Cmdlets.ServiceBus.Models.IArmDisasterRecovery" data-throw-if-not-resolved="False" />
examples:
- title: 'Example 1: Create a disaster recovery Alias'
  description: |-
    ```powershell
    New-AzServiceBusGeoDRConfiguration -Name myAlias -ResourceGroupName myResourceGroup -NamespaceName myPrimaryNamespace -PartnerNamespace "/subscriptions/0000000000000/resourceGroups/myResourceGroup/providers/Microsoft.ServiceBus/namespaces/mySecondaryNamespace"
    ```

    ```output
    AlternateName                     :
    Id                                : /subscriptions/0000000000000/resourceGroups/myResourceGroup/providers/Microsoft.ServiceBus/namespaces/myPrimaryNamespace/disasterRecoveryCon
                                        figs/myAlias
    Location                          :
    Name                              : myAlias
    PartnerNamespace                  : /subscriptions/0000000000000/resourceGroups/myResourceGroup/providers/Microsoft.ServiceBus/namespaces/mySecondaryNamespace
    PendingReplicationOperationsCount :
    ProvisioningState                 : Succeeded
    ResourceGroupName                 : myResourceGroup
    Role                              : Primary
    ```

    Creates a Disaster Recovery configuration which sets `mySecondaryNamespace` as secondary to `myPrimaryNamespace`.
metadata:
  content_git_url: https://github.com/Azure/azure-powershell/blob/main/src/ServiceBus/ServiceBus/help/New-AzServiceBusGeoDRConfiguration.md
  document type: cmdlet
  external help file: Az.ServiceBus-help.xml
  HelpUri: https://learn.microsoft.com/powershell/module/az.servicebus/new-azservicebusgeodrconfiguration
  Module Name: Az.ServiceBus
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/main/src/ServiceBus/ServiceBus/help/New-AzServiceBusGeoDRConfiguration.md
  PlatyPS schema version: 2024-05-01
