### YamlMime:PowerShellCmdlet1
uid: Az.DevCenter.Get-AzDevCenterUserEnvironmentDefinition
name: Get-AzDevCenterUserEnvironmentDefinition
module: Az.DevCenter
isPreview: false
summary: |-
  Get an environment definition from a catalog.
description: |-
  Get an environment definition from a catalog.
parameters:
  cmdletParameters:
  - name: CatalogName
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      The name of the catalog
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: Get
      position: Named
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    - name: List1
      position: Named
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    - name: List1ByDevCenter
      position: Named
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    - name: GetByDevCenter
      position: Named
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: DefaultProfile
    type: <xref href="System.Management.Automation.PSObject" data-throw-if-not-resolved="False" />
    description: |-
      The DefaultProfile parameter is not functional.
      Use the SubscriptionId parameter when available if executing the cmdlet against a different subscription.
    aliases:
    - AzureRMContext
    - AzureCredential
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: DefinitionName
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      The name of the environment definition
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: Get
      position: Named
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    - name: GetByDevCenter
      position: Named
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: DevCenterName
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      The DevCenter upon which to execute operations.
    aliases:
    - DevCenter
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: GetViaIdentityByDevCenter
      position: Named
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    - name: List1ByDevCenter
      position: Named
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    - name: ListByDevCenter
      position: Named
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    - name: GetByDevCenter
      position: Named
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: Endpoint
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      The DevCenter-specific URI to operate on.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: List
      position: Named
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    - name: Get
      position: Named
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    - name: GetViaIdentity
      position: Named
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    - name: List1
      position: Named
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: InputObject
    type: <xref href="Microsoft.Azure.PowerShell.Cmdlets.DevCenterdata.Models.IDevCenterdataIdentity" data-throw-if-not-resolved="False" />
    description: |-
      Identity Parameter
      To construct, see NOTES section for INPUTOBJECT properties and create a hash table.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: GetViaIdentity
      position: Named
      isRequired: true
      valueFromPipeline: true
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    - name: GetViaIdentityByDevCenter
      position: Named
      isRequired: true
      valueFromPipeline: true
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: ProjectName
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      The DevCenter Project upon which to execute operations.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: List
      position: Named
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    - name: Get
      position: Named
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    - name: List1
      position: Named
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    - name: List1ByDevCenter
      position: Named
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    - name: ListByDevCenter
      position: Named
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    - name: GetByDevCenter
      position: Named
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  commonParameters: |-
    This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable,
    -InformationAction, -InformationVariable, -OutBuffer, -OutVariable, -PipelineVariable,
    -ProgressAction, -Verbose, -WarningAction, and -WarningVariable. For more information, see
    [about_CommonParameters](https://go.microsoft.com/fwlink/?LinkID=113216).
syntaxes:
- syntax: |-
    ```Syntax
    Get-AzDevCenterUserEnvironmentDefinition
        -Endpoint <String>
        -ProjectName <String>
        [-DefaultProfile <PSObject>]
        [<CommonParameters>]
    ```
  parameterSetName: List
  isDefault: true
- syntax: |-
    ```Syntax
    Get-AzDevCenterUserEnvironmentDefinition
        -Endpoint <String>
        -ProjectName <String>
        -CatalogName <String>
        -DefinitionName <String>
        [-DefaultProfile <PSObject>]
        [<CommonParameters>]
    ```
  parameterSetName: Get
  isDefault: false
- syntax: |-
    ```Syntax
    Get-AzDevCenterUserEnvironmentDefinition
        -Endpoint <String>
        -InputObject <IDevCenterdataIdentity>
        [-DefaultProfile <PSObject>]
        [<CommonParameters>]
    ```
  parameterSetName: GetViaIdentity
  isDefault: false
- syntax: |-
    ```Syntax
    Get-AzDevCenterUserEnvironmentDefinition
        -Endpoint <String>
        -ProjectName <String>
        -CatalogName <String>
        [-DefaultProfile <PSObject>]
        [<CommonParameters>]
    ```
  parameterSetName: List1
  isDefault: false
- syntax: |-
    ```Syntax
    Get-AzDevCenterUserEnvironmentDefinition
        -DevCenterName <String>
        -InputObject <IDevCenterdataIdentity>
        [-DefaultProfile <PSObject>]
        [<CommonParameters>]
    ```
  parameterSetName: GetViaIdentityByDevCenter
  isDefault: false
- syntax: |-
    ```Syntax
    Get-AzDevCenterUserEnvironmentDefinition
        -DevCenterName <String>
        -ProjectName <String>
        -CatalogName <String>
        [-DefaultProfile <PSObject>]
        [<CommonParameters>]
    ```
  parameterSetName: List1ByDevCenter
  isDefault: false
- syntax: |-
    ```Syntax
    Get-AzDevCenterUserEnvironmentDefinition
        -DevCenterName <String>
        -ProjectName <String>
        [-DefaultProfile <PSObject>]
        [<CommonParameters>]
    ```
  parameterSetName: ListByDevCenter
  isDefault: false
- syntax: |-
    ```Syntax
    Get-AzDevCenterUserEnvironmentDefinition
        -DevCenterName <String>
        -ProjectName <String>
        -CatalogName <String>
        -DefinitionName <String>
        [-DefaultProfile <PSObject>]
        [<CommonParameters>]
    ```
  parameterSetName: GetByDevCenter
  isDefault: false
inputs:
- name: <xref href="Microsoft.Azure.PowerShell.Cmdlets.DevCenterdata.Models.IDevCenterdataIdentity" data-throw-if-not-resolved="False" />
outputs:
- name: <xref href="Microsoft.Azure.PowerShell.Cmdlets.DevCenterdata.Models.Api20231001Preview.IEnvironmentDefinition" data-throw-if-not-resolved="False" />
examples:
- title: 'Example 1: List environment definitions by endpoint and project'
  description: |-
    ```powershell

    ```

    ```powershell
    Get-AzDevCenterUserEnvironmentDefinition -Endpoint "https://8a40af38-3b4c-4672-a6a4-5e964b1870ed-contosodevcenter.centralus.devcenter.azure.com/" -ProjectName DevProject
    ```

    This command lists environment definitions under the project "DevProject".
- title: 'Example 2: List environment definitions by dev center and project'
  description: |-
    ```powershell
    Get-AzDevCenterUserEnvironmentDefinition -DevCenterName Contoso -ProjectName DevProject
    ```

    This command lists environment definitions under the project "DevProject".
- title: 'Example 3: List environment definitions by endpoint, catalog, and project'
  description: |-
    ```powershell
    Get-AzDevCenterUserEnvironmentDefinition -Endpoint "https://8a40af38-3b4c-4672-a6a4-5e964b1870ed-contosodevcenter.centralus.devcenter.azure.com/" -ProjectName DevProject -CatalogName CentralCatalog
    ```

    This command lists environment definitions under the project "DevProject" and the catalog "CentralCatalog".
- title: 'Example 4: List environment definitions by dev center, catalog, and project'
  description: |-
    ```powershell
    Get-AzDevCenterUserEnvironmentDefinition -DevCenterName Contoso -ProjectName DevProject -CatalogName CentralCatalog
    ```

    This command lists environment definitions under the project "DevProject" and the catalog "CentralCatalog".
- title: 'Example 5: Get an environment definition by endpoint'
  description: |-
    ```powershell
    Get-AzDevCenterUserEnvironmentDefinition -Endpoint "https://8a40af38-3b4c-4672-a6a4-5e964b1870ed-contosodevcenter.centralus.devcenter.azure.com/" -ProjectName DevProject -CatalogName CentralCatalog  -DefinitionName Sandbox
    ```

    This command gets the environment definition "Sandbox" under the project "DevProject" and the catalog "CentralCatalog".
- title: 'Example 6: Get an environment definition by dev center'
  description: |-
    ```powershell
    Get-AzDevCenterUserEnvironmentDefinition -DevCenterName Contoso -ProjectName DevProject -CatalogName CentralCatalog -DefinitionName Sandbox
    ```

    This command gets the environment definition "Sandbox" under the project "DevProject" and the catalog "CentralCatalog".
- title: 'Example 7: Get an environment definition by endpoint and InputObject'
  description: |-
    ```powershell
    $envInput = @{"CatalogName" = "CentralCatalog"; "ProjectName" = "DevProject"; "DefinitionName" = "Sandbox" }
    Get-AzDevCenterUserEnvironmentDefinition -Endpoint "https://8a40af38-3b4c-4672-a6a4-5e964b1870ed-contosodevcenter.centralus.devcenter.azure.com/" -InputObject $envInput
    ```

    This command gets the environment definition "Sandbox" under the project "DevProject" and the catalog "CentralCatalog".
- title: 'Example 8: Get an environment definition by dev center and InputObject'
  description: |-
    ```powershell
    $envInput = @{"CatalogName" = "CentralCatalog"; "ProjectName" = "DevProject"; "DefinitionName" = "Sandbox" }
    Get-AzDevCenterUserEnvironmentDefinition -DevCenterName Contoso -InputObject $envInput
    ```

    This command gets the environment definition "Sandbox" under the project "DevProject" and the catalog "CentralCatalog".
metadata:
  content_git_url: https://github.com/Azure/azure-powershell/blob/main/src/DevCenter/DevCenter/help/Get-AzDevCenterUserEnvironmentDefinition.md
  document type: cmdlet
  external help file: Az.DevCenter-help.xml
  HelpUri: https://learn.microsoft.com/powershell/module/az.devcenter/get-azdevcenteruserenvironmentdefinition
  Module Name: Az.DevCenter
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/main/src/DevCenter/DevCenter/help/Get-AzDevCenterUserEnvironmentDefinition.md
  PlatyPS schema version: 2024-05-01
