### YamlMime:PowerShellCmdlet1
uid: Az.ApplicationInsights.New-AzApplicationInsightsWorkbookTemplate
name: New-AzApplicationInsightsWorkbookTemplate
module: Az.ApplicationInsights
isPreview: false
summary: |-
  Create a new workbook template.
description: |-
  Create a new workbook template.
parameters:
  cmdletParameters:
  - name: Author
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      Information about the author of the workbook template.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: Confirm
    type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
    description: |-
      Prompts you for confirmation before running the cmdlet.
    aliases:
    - cf
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: DefaultProfile
    type: <xref href="System.Management.Automation.PSObject" data-throw-if-not-resolved="False" />
    description: |-
      The DefaultProfile parameter is not functional.
      Use the SubscriptionId parameter when available if executing the cmdlet against a different subscription.
    aliases:
    - AzureRMContext
    - AzureCredential
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: Gallery
    type: <xref href="Microsoft.Azure.PowerShell.Cmdlets.ApplicationInsights.Models.Api20201120.IWorkbookTemplateGallery" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
    description: |-
      Workbook galleries supported by the template.
      To construct, see NOTES section for GALLERY properties and create a hash table.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: Localized
    type: <xref href="System.Collections.Hashtable" data-throw-if-not-resolved="False" />
    description: |-
      Key value pair of localized gallery.
      Each key is the locale code of languages supported by the Azure portal.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: Location
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      Resource location
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: Name
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      The name of the Application Insights component resource.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: Priority
    type: <xref href="System.Int32" data-throw-if-not-resolved="False" />
    description: |-
      Priority of the template.
      Determines which template to open when a workbook gallery is opened in viewer mode.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: ResourceGroupName
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      The name of the resource group.
      The name is case insensitive.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: SubscriptionId
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      The ID of the target subscription.
    defaultValue: (Get-AzContext).Subscription.Id
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: Tag
    type: <xref href="System.Collections.Hashtable" data-throw-if-not-resolved="False" />
    description: |-
      Resource tags
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: TemplateData
    type: <xref href="System.Collections.Hashtable" data-throw-if-not-resolved="False" />
    description: |-
      Valid JSON object containing workbook template payload.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: WhatIf
    type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
    description: |-
      Shows what would happen if the cmdlet runs.
      The cmdlet is not run.
    aliases:
    - wi
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  commonParameters: |-
    This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable,
    -InformationAction, -InformationVariable, -OutBuffer, -OutVariable, -PipelineVariable,
    -ProgressAction, -Verbose, -WarningAction, and -WarningVariable. For more information, see
    [about_CommonParameters](https://go.microsoft.com/fwlink/?LinkID=113216).
syntaxes:
- syntax: |-
    ```Syntax
    New-AzApplicationInsightsWorkbookTemplate
        -Name <String>
        -ResourceGroupName <String>
        [-SubscriptionId <String>]
        -Location <String>
        [-Author <String>]
        [-Gallery <IWorkbookTemplateGallery[]>]
        [-Localized <Hashtable>]
        [-Priority <Int32>]
        [-Tag <Hashtable>]
        [-TemplateData <Hashtable>]
        [-DefaultProfile <PSObject>]
        [-WhatIf]
        [-Confirm]
        [<CommonParameters>]
    ```
  parameterSetName: Default
  isDefault: true
outputs:
- name: <xref href="Microsoft.Azure.PowerShell.Cmdlets.ApplicationInsights.Models.Api20201120.IWorkbookTemplate" data-throw-if-not-resolved="False" />
examples:
- title: 'Example 1: Create a new workbook template'
  description: |-
    ```powershell
    $gallery = New-AzApplicationInsightsWorkbookTemplateGalleryObject -Category "Failures" -Name "Simple Template" -Type 'tsg' -ResourceType "microsoft.insights/components" -Order 100
    $data = @{
      "version"= "Notebook/1.0";
      "items"= @(
        @{
          "type"= 1;
          "content"= @{
            "json"= "## New workbook\n---\n\nWelcome to your new workbook.  This area will display text formatted as markdown.\n\n\nWe've included a basic analytics query to get you started. Use the `Edit` button below each section to configure it or add more sections."
          };
          "name"= "text - 2"
        },
        @{
          "type"= 3;
          "content"= @{
            "version"= "KqlItem/1.0";
            "query"= "union withsource=TableName *\n| summarize Count=count() by TableName\n| render barchart";
            "size"= 1;
            "exportToExcelOptions"= "visible";
            "queryType"= 0;
            "resourceType"= "microsoft.operationalinsights/workspaces"
          };
          "name"= "query - 2"
        }
      );
      "styleSettings"= @{};
      "$schema"= "https://github.com/Microsoft/Application-Insights-Workbooks/blob/master/schema/workbook.json"
    }

    New-AzApplicationInsightsWorkbookTemplate -ResourceGroupName resourceGroup -Name 'workbooktemplate-pwsh01' -Location 'westus2' -Gallery $gallery -TemplateData $data -Priority 1
    ```

    ```output
    ResourceGroupName       Name                    Location
    -----------------       ----                    --------
    appinsights-hkrs2v-test workbooktemplate-pwsh01 westus2
    ```

    Create a new workbook template.
metadata:
  content_git_url: https://github.com/Azure/azure-powershell/blob/main/src/ApplicationInsights/ApplicationInsights/help/New-AzApplicationInsightsWorkbookTemplate.md
  document type: cmdlet
  external help file: Az.ApplicationInsights-help.xml
  HelpUri: https://learn.microsoft.com/powershell/module/az.applicationinsights/new-azapplicationinsightsworkbooktemplate
  Module Name: Az.ApplicationInsights
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/main/src/ApplicationInsights/ApplicationInsights/help/New-AzApplicationInsightsWorkbookTemplate.md
  PlatyPS schema version: 2024-05-01
