### YamlMime:PowerShellCmdlet1
uid: Az.ApplicationInsights.New-AzApplicationInsightsWorkbook
name: New-AzApplicationInsightsWorkbook
module: Az.ApplicationInsights
isPreview: false
summary: |-
  Create a new workbook.
description: |-
  Create a new workbook.
parameters:
  cmdletParameters:
  - name: Category
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      Workbook category, as defined by the user at creation time.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: Confirm
    type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
    description: |-
      Prompts you for confirmation before running the cmdlet.
    aliases:
    - cf
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: DefaultProfile
    type: <xref href="System.Management.Automation.PSObject" data-throw-if-not-resolved="False" />
    description: |-
      The DefaultProfile parameter is not functional.
      Use the SubscriptionId parameter when available if executing the cmdlet against a different subscription.
    aliases:
    - AzureRMContext
    - AzureCredential
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: Description
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      The description of the workbook.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: DisplayName
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      The user-defined name (display name) of the workbook.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: Etag
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      Resource etag
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: IdentityType
    type: <xref href="Microsoft.Azure.PowerShell.Cmdlets.ApplicationInsights.Support.ManagedServiceIdentityType" data-throw-if-not-resolved="False" />
    description: |-
      Type of managed service identity (where both SystemAssigned and UserAssigned types are allowed).
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: IdentityUserAssignedIdentity
    type: <xref href="System.Collections.Hashtable" data-throw-if-not-resolved="False" />
    description: |-
      The set of user assigned identities associated with the resource.
      The userAssignedIdentities dictionary keys will be ARM resource ids in the form: '/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ManagedIdentity/userAssignedIdentities/{identityName}.
      The dictionary values can be empty objects ({}) in requests.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: LinkedSourceId
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      Azure Resource Id that will fetch all linked workbooks.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: Location
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      The geo-location where the resource lives
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: Name
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      The name of the resource.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: ResourceGroupName
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      The name of the resource group.
      The name is case insensitive.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: SerializedData
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      Configuration of this particular workbook.
      Configuration data is a string containing valid JSON
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: SourceId
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      ResourceId for a source resource.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: SourceTag
    type: <xref href="System.String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
    description: |-
      Being deprecated, please use the other tags field
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: StorageUri
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      The resourceId to the storage account when bring your own storage is used
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: SubscriptionId
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      The ID of the target subscription.
    defaultValue: (Get-AzContext).Subscription.Id
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: Tag
    type: <xref href="System.Collections.Hashtable" data-throw-if-not-resolved="False" />
    description: |-
      Resource tags.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: Version
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      Workbook schema version format, like 'Notebook/1.0', which should match the workbook in serializedData
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: WhatIf
    type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
    description: |-
      Shows what would happen if the cmdlet runs.
      The cmdlet is not run.
    aliases:
    - wi
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  commonParameters: |-
    This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable,
    -InformationAction, -InformationVariable, -OutBuffer, -OutVariable, -PipelineVariable,
    -ProgressAction, -Verbose, -WarningAction, and -WarningVariable. For more information, see
    [about_CommonParameters](https://go.microsoft.com/fwlink/?LinkID=113216).
syntaxes:
- syntax: |-
    ```Syntax
    New-AzApplicationInsightsWorkbook
        -Name <String>
        -ResourceGroupName <String>
        [-SubscriptionId <String>]
        [-LinkedSourceId <String>]
        -Location <String>
        [-Category <String>]
        [-Description <String>]
        [-DisplayName <String>]
        [-Etag <String>]
        [-IdentityType <ManagedServiceIdentityType>]
        [-IdentityUserAssignedIdentity <Hashtable>]
        [-SerializedData <String>]
        [-SourceId <String>]
        [-SourceTag <String[]>]
        [-StorageUri <String>]
        [-Tag <Hashtable>]
        [-Version <String>]
        [-DefaultProfile <PSObject>]
        [-WhatIf]
        [-Confirm]
        [<CommonParameters>]
    ```
  parameterSetName: Default
  isDefault: true
outputs:
- name: <xref href="Microsoft.Azure.PowerShell.Cmdlets.ApplicationInsights.Models.Api20220401.IWorkbook" data-throw-if-not-resolved="False" />
examples:
- title: 'Example 1: Create a new workbook'
  description: |-
    ```powershell
    $name = (New-Guid).ToString()
    New-AzApplicationInsightsWorkbook -ResourceGroupName appinsights-hkrs2v-test -Name $name -Location westus2 -DisplayName "$name-display" -SourceId "/subscriptions/9e223dbe-3399-4e19-88eb-0975f02ac87f/resourcegroups/appinsights-hkrs2v-test/providers/microsoft.insights/components/appinsights-48mah3-pwsh" -Category 'workbook' -SerializedData $null
    ```

    ```output
    ResourceGroupName       Name                                 DisplayName Location Kind Category
    -----------------       ----                                 ----------- -------- ---- --------
    appinsights-hkrs2v-test 2e47417f-c136-44c0-b78f-7a4ca35fd9d1 pwsh01      westus2  user workbook
    ```

    This command create a new workbook.
metadata:
  content_git_url: https://github.com/Azure/azure-powershell/blob/main/src/ApplicationInsights/ApplicationInsights/help/New-AzApplicationInsightsWorkbook.md
  document type: cmdlet
  external help file: Az.ApplicationInsights-help.xml
  HelpUri: https://learn.microsoft.com/powershell/module/az.applicationinsights/new-azapplicationinsightsworkbook
  Module Name: Az.ApplicationInsights
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/main/src/ApplicationInsights/ApplicationInsights/help/New-AzApplicationInsightsWorkbook.md
  PlatyPS schema version: 2024-05-01
