### YamlMime:PowerShellCmdlet1
uid: Az.Synapse.New-AzSynapseGitRepositoryConfig
name: New-AzSynapseGitRepositoryConfig
module: Az.Synapse
isPreview: false
summary: |-
  Creates Git repository configuration.
description: |-
  This **New-AzSynapseGitRepositoryConfig** cmdlets creates a Git repository configuration which can be used in creating or updating a workspace.
parameters:
  cmdletParameters:
  - name: AccountName
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      GitHub or DevOps account name used for the repository.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: CollaborationBranch
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      Select the branch name where you will collaborate with others and from which you will publish.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: DefaultProfile
    type: <xref href="Microsoft.Azure.Commands.Common.Authentication.Abstractions.Core.IAzureContextContainer" data-throw-if-not-resolved="False" />
    description: |-
      The credentials, account, tenant, and subscription used for communication with Azure.
    aliases:
    - AzContext
    - AzureRmContext
    - AzureCredential
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: HostName
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      GitHub Enterprise host name.
      For example: `https://github.mydomain.com`
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: LastCommitId
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      The last published commit Id.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: ProjectName
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      The project name you are connecting, only specify it when you choose DevOps.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: RepositoryName
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      The name of the repository you are connecting.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: RepositoryType
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      Select the repository type that you want to use to store your artifacts for this Synapse Analytics workspace, the type include DevOps and GitHub.
    acceptedValues:
    - GitHub
    - AzureDevOpsGit
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: RootFolder
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      Displays the name of the folder to the location of your Azure Data Factory JSON resources are imported.
      The default value is /
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: TenantId
    type: <xref href="System.Guid" data-throw-if-not-resolved="False" />
    description: |-
      Select the tenant Id to use when signing in into the Azure DevOps Git repository.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  commonParameters: |-
    This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable,
    -InformationAction, -InformationVariable, -OutBuffer, -OutVariable, -PipelineVariable,
    -ProgressAction, -Verbose, -WarningAction, and -WarningVariable. For more information, see
    [about_CommonParameters](https://go.microsoft.com/fwlink/?LinkID=113216).
syntaxes:
- syntax: |-
    ```Syntax
    New-AzSynapseGitRepositoryConfig
        -RepositoryType <String>
        [-HostName <String>]
        -AccountName <String>
        [-ProjectName <String>]
        -RepositoryName <String>
        -CollaborationBranch <String>
        [-RootFolder <String>]
        [-TenantId <Guid>]
        [-LastCommitId <String>]
        [-DefaultProfile <IAzureContextContainer>]
        [<CommonParameters>]
    ```
  parameterSetName: Default
  isDefault: true
inputs:
- name: <xref href="None" data-throw-if-not-resolved="False" />
outputs:
- name: <xref href="Microsoft.Azure.Commands.Synapse.Models.PSWorkspaceRepositoryConfiguration" data-throw-if-not-resolved="False" />
examples:
- title: Example 1
  description: |-
    ```powershell
    $config = New-AzSynapseGitRepositoryConfig -RepositoryType GitHub -AccountName ContosoAccount -RepositoryName ContosoRepo -CollaborationBranch main
    $password = ConvertTo-SecureString -String "****" -AsPlainText -Force
    $creds = New-Object System.Management.Automation.PSCredential ("ContosoUser", $password)
    New-AzSynapseWorkspace -ResourceGroupName ContosoResourceGroup -Name ContosoWorkspace -Location northeurope -DefaultDataLakeStorageAccountName ContosoAdlGen2Storage -DefaultDataLakeStorageFilesystem ContosoFileSystem -SqlAdministratorLoginCredential $creds -AsJob -GitRepository $config
    ```

    The first command creates a Git repository configuration. Then the rest methods uses the configuration to creates a new Synapse workspace.
metadata:
  content_git_url: https://github.com/Azure/azure-powershell/blob/main/src/Synapse/Synapse/help/New-AzSynapseGitRepositoryConfig.md
  document type: cmdlet
  external help file: Microsoft.Azure.PowerShell.Cmdlets.Synapse.dll-Help.xml
  HelpUri: https://learn.microsoft.com/powershell/module/az.synapse/new-azsynapsegitrepositoryconfig
  Module Name: Az.Synapse
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/main/src/Synapse/Synapse/help/New-AzSynapseGitRepositoryConfig.md
  PlatyPS schema version: 2024-05-01
