### YamlMime:PowerShellCmdlet1
uid: Az.Network.Add-AzVirtualNetworkGatewayIpConfig
name: Add-AzVirtualNetworkGatewayIpConfig
module: Az.Network
isPreview: false
summary: |-
  Adds an IP configuration to a virtual network gateway.
description: |-
  The **Add-AzVirtualNetworkGatewayIpConfig** cmdlet adds an IP configuration to a virtual network gateway.
parameters:
  cmdletParameters:
  - name: Confirm
    type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
    description: |-
      Prompts you for confirmation before running the cmdlet.
    aliases:
    - cf
    defaultValue: "False"
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: DefaultProfile
    type: <xref href="IAzureContextContainer" data-throw-if-not-resolved="False" />
    description: |-
      The credentials, account, tenant, and subscription used for communication with azure.
    aliases:
    - AzureRmContext
    - AzureCredential
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: Name
    type: <xref href="String" data-throw-if-not-resolved="False" />
    description: |-
      Specifies the name of the gateway IP configuration to add.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: PrivateIpAddress
    type: <xref href="String" data-throw-if-not-resolved="False" />
    description: |-
      Specifies the private IP address.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: PublicIpAddress
    type: <xref href="PSPublicIpAddress" data-throw-if-not-resolved="False" />
    description: |-
      Specifies the public IP address.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: SetByResource
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: PublicIpAddressId
    type: <xref href="String" data-throw-if-not-resolved="False" />
    description: |-
      Specifies the ID of the public IP address.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: SetByResourceId
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: Subnet
    type: <xref href="PSSubnet" data-throw-if-not-resolved="False" />
    description: |-
      Specifies a **PSSubnet** object.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: SetByResource
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: SubnetId
    type: <xref href="String" data-throw-if-not-resolved="False" />
    description: |-
      Specifies the ID of the subnet.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: SetByResourceId
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: VirtualNetworkGateway
    type: <xref href="PSVirtualNetworkGateway" data-throw-if-not-resolved="False" />
    description: |-
      Specifies a **PSVirtualNetworkGateway** object.
      This cmdlet modifies the **PSVirtualNetworkGateway** object that you specify.
      You can use the Get-AzVirtualNetworkGateway cmdlet to retrieve a **PSVirtualNetworkGateway** object.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: true
      valueFromPipeline: true
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: WhatIf
    type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
    description: |-
      Shows what would happen if the cmdlet runs.
      The cmdlet is not run.
    aliases:
    - wi
    defaultValue: "False"
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  commonParameters: |-
    This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable,
    -InformationAction, -InformationVariable, -OutBuffer, -OutVariable, -PipelineVariable,
    -ProgressAction, -Verbose, -WarningAction, and -WarningVariable. For more information, see
    [about_CommonParameters](https://go.microsoft.com/fwlink/?LinkID=113216).
syntaxes:
- syntax: |-
    ```Syntax
    Add-AzVirtualNetworkGatewayIpConfig
        -VirtualNetworkGateway <PSVirtualNetworkGateway>
        -Name <String>
        [-PrivateIpAddress <String>]
        [-SubnetId <String>]
        [-PublicIpAddressId <String>]
        [-DefaultProfile <IAzureContextContainer>]
        [-WhatIf]
        [-Confirm]
        [<CommonParameters>]
    ```
  parameterSetName: SetByResourceId
  isDefault: false
- syntax: |-
    ```Syntax
    Add-AzVirtualNetworkGatewayIpConfig
        -VirtualNetworkGateway <PSVirtualNetworkGateway>
        -Name <String>
        [-PrivateIpAddress <String>]
        [-Subnet <PSSubnet>]
        [-PublicIpAddress <PSPublicIpAddress>]
        [-DefaultProfile <IAzureContextContainer>]
        [-WhatIf]
        [-Confirm]
        [<CommonParameters>]
    ```
  parameterSetName: SetByResource
  isDefault: false
inputs:
- name: <xref href="PSVirtualNetworkGateway" data-throw-if-not-resolved="False" />
  description: |-
    Parameter 'VirtualNetworkGateway' accepts value of type 'PSVirtualNetworkGateway' from the pipeline
outputs:
- name: <xref href="Microsoft.Azure.Commands.Network.Models.PSVirtualNetworkGateway" data-throw-if-not-resolved="False" />
examples:
- title: '1:'
  description: |-
    ```

    ```
links:
- text: Get-AzVirtualNetworkGateway
  href: ./Get-AzVirtualNetworkGateway.yml
- text: New-AzVirtualNetworkGatewayIpConfig
  href: ./New-AzVirtualNetworkGatewayIpConfig.yml
- text: Remove-AzVirtualNetworkGatewayIpConfig
  href: ./Remove-AzVirtualNetworkGatewayIpConfig.yml
metadata:
  content_git_url: https://github.com/Azure/azure-powershell/blob/Azs-tzl/src/Network/Network/help/Add-AzVirtualNetworkGatewayIpConfig.md
  document type: cmdlet
  external help file: Microsoft.Azure.PowerShell.Cmdlets.Network.dll-Help.xml
  HelpUri: https://learn.microsoft.com/en-us/powershell/module/az.network/add-azvirtualnetworkgatewayipconfig
  Module Name: Az.Network
  ms.assetid: BCB64535-FF37-46EF-85AF-7286BB67787B
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/Azs-tzl/src/Network/Network/help/Add-AzVirtualNetworkGatewayIpConfig.md
  PlatyPS schema version: 2024-05-01
