### YamlMime:PowerShellCmdlet1
uid: Az.Network.Remove-AzApplicationGatewayHttpListener
name: Remove-AzApplicationGatewayHttpListener
module: Az.Network
isPreview: false
summary: |-
  Removes an HTTP listener from an application gateway.
description: |-
  The **Remove-AzApplicationGatewayHttpListener** cmdlet removes an HTTP listener from an Azure application gateway.
parameters:
  cmdletParameters:
  - name: ApplicationGateway
    type: <xref href="PSApplicationGateway" data-throw-if-not-resolved="False" />
    description: |-
      Specifies the application gateway from which to remove an HTTP listener.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: true
      valueFromPipeline: true
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: DefaultProfile
    type: <xref href="IAzureContextContainer" data-throw-if-not-resolved="False" />
    description: |-
      The credentials, account, tenant, and subscription used for communication with azure.
    aliases:
    - AzureRmContext
    - AzureCredential
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: Name
    type: <xref href="String" data-throw-if-not-resolved="False" />
    description: |-
      Specifies the name of the HTTP listener that this cmdlet removes.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  commonParameters: |-
    This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable,
    -InformationAction, -InformationVariable, -OutBuffer, -OutVariable, -PipelineVariable,
    -ProgressAction, -Verbose, -WarningAction, and -WarningVariable. For more information, see
    [about_CommonParameters](https://go.microsoft.com/fwlink/?LinkID=113216).
syntaxes:
- syntax: |-
    ```Syntax
    Remove-AzApplicationGatewayHttpListener
        -Name <String>
        -ApplicationGateway <PSApplicationGateway>
        [-DefaultProfile <IAzureContextContainer>]
        [<CommonParameters>]
    ```
  parameterSetName: Default
  isDefault: true
inputs:
- name: <xref href="System.String" data-throw-if-not-resolved="False" />
outputs:
- name: <xref href="Microsoft.Azure.Commands.Network.Models.PSApplicationGatewayHttpListener" data-throw-if-not-resolved="False" />
examples:
- title: 'Example 1: Remove an application gateway HTTP listener'
  description: |-
    ```
    PS C:\>$AppGw = Get-AzApplicationGateway -Name "ApplicationGateway01" -ResourceGroupName "ResourceGroup01"
    PS C:\> Remove-AzApplicationGatewayHttpListener -ApplicationGateway $AppGw -Name "Listener02"
    ```

    The first command gets an application gateway and stores it in the $AppGw variable.

    The second command removes the HTTP listener named Listener02 from the application gateway stored in $AppGw.
links:
- text: Add-AzApplicationGatewayHttpListener
  href: ./Add-AzApplicationGatewayHttpListener.yml
- text: Get-AzApplicationGatewayHttpListener
  href: ./Get-AzApplicationGatewayHttpListener.yml
- text: New-AzApplicationGatewayHttpListener
  href: ./New-AzApplicationGatewayHttpListener.yml
- text: Set-AzApplicationGatewayHttpListener
  href: ./Set-AzApplicationGatewayHttpListener.yml
metadata:
  content_git_url: https://github.com/Azure/azure-powershell/blob/Azs-tzl/src/Network/Network/help/Remove-AzApplicationGatewayHttpListener.md
  document type: cmdlet
  external help file: Microsoft.Azure.PowerShell.Cmdlets.Network.dll-Help.xml
  HelpUri: https://learn.microsoft.com/en-us/powershell/module/az.network/remove-azapplicationgatewayhttplistener
  Module Name: Az.Network
  ms.assetid: 6C90AF6C-3193-4D75-A78F-3EC315C6D7DF
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/Azs-tzl/src/Network/Network/help/Remove-AzApplicationGatewayHttpListener.md
  PlatyPS schema version: 2024-05-01
