### YamlMime:PowerShellCmdlet1
uid: Az.Network.Remove-AzApplicationGatewayBackendAddressPool
name: Remove-AzApplicationGatewayBackendAddressPool
module: Az.Network
isPreview: false
summary: |-
  Removes a back-end address pool from an application gateway.
description: |-
  The **Remove-AzApplicationGatewayBackendAddressPool** cmdlet removes a back-end address pool from an Azure application gateway.
parameters:
  cmdletParameters:
  - name: ApplicationGateway
    type: <xref href="PSApplicationGateway" data-throw-if-not-resolved="False" />
    description: |-
      Specifies the application gateway from which this cmdlet removes a back-end address pool.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: true
      valueFromPipeline: true
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: Confirm
    type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
    description: |-
      Prompts you for confirmation before running the cmdlet.
    aliases:
    - cf
    defaultValue: "False"
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: DefaultProfile
    type: <xref href="IAzureContextContainer" data-throw-if-not-resolved="False" />
    description: |-
      The credentials, account, tenant, and subscription used for communication with azure.
    aliases:
    - AzureRmContext
    - AzureCredential
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: Name
    type: <xref href="String" data-throw-if-not-resolved="False" />
    description: |-
      Specifies the name of the back-end address pool that this cmdlet removes.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: WhatIf
    type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
    description: |-
      Shows what would happen if the cmdlet runs.
      The cmdlet is not run.
    aliases:
    - wi
    defaultValue: "False"
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  commonParameters: |-
    This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable,
    -InformationAction, -InformationVariable, -OutBuffer, -OutVariable, -PipelineVariable,
    -ProgressAction, -Verbose, -WarningAction, and -WarningVariable. For more information, see
    [about_CommonParameters](https://go.microsoft.com/fwlink/?LinkID=113216).
syntaxes:
- syntax: |-
    ```Syntax
    Remove-AzApplicationGatewayBackendAddressPool
        -Name <String>
        -ApplicationGateway <PSApplicationGateway>
        [-DefaultProfile <IAzureContextContainer>]
        [-WhatIf]
        [-Confirm]
        [<CommonParameters>]
    ```
  parameterSetName: Default
  isDefault: true
inputs:
- name: <xref href="System.String" data-throw-if-not-resolved="False" />
outputs:
- name: <xref href="Microsoft.Azure.Commands.Network.Models.PSApplicationGatewayBackendAddressPool" data-throw-if-not-resolved="False" />
examples:
- title: 'Example 1: Remove a back-end address pool from an application gateway'
  description: |-
    ```
    PS C:\>$AppGw = Get-AzApplicationGateway -Name "ApplicationGateway01" -ResourceGroupName "ResourceGroup01"
    PS C:\> Remove-AzApplicationGatewayBackendAddressPool -ApplicationGateway $AppGw -Name "BackEndPool02"
    ```

    The first command gets the application gateway named ApplicationGateway01 belonging to the resource group named ResourceGroup01 and saves it in the $AppGw variable.

    The second command removes the back-end address pool named BackEndPool02 from the application gateway.
links:
- text: Add-AzApplicationGatewayBackendAddressPool
  href: ./Add-AzApplicationGatewayBackendAddressPool.yml
- text: Get-AzApplicationGatewayBackendAddressPool
  href: ./Get-AzApplicationGatewayBackendAddressPool.yml
- text: New-AzApplicationGatewayBackendAddressPool
  href: ./New-AzApplicationGatewayBackendAddressPool.yml
- text: Set-AzApplicationGatewayBackendAddressPool
  href: ./Set-AzApplicationGatewayBackendAddressPool.yml
metadata:
  content_git_url: https://github.com/Azure/azure-powershell/blob/Azs-tzl/src/Network/Network/help/Remove-AzApplicationGatewayBackendAddressPool.md
  document type: cmdlet
  external help file: Microsoft.Azure.PowerShell.Cmdlets.Network.dll-Help.xml
  HelpUri: https://learn.microsoft.com/en-us/powershell/module/az.network/remove-azapplicationgatewaybackendaddresspool
  Module Name: Az.Network
  ms.assetid: F34C5D18-C505-4815-9DDB-C563E205515C
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/Azs-tzl/src/Network/Network/help/Remove-AzApplicationGatewayBackendAddressPool.md
  PlatyPS schema version: 2024-05-01
