### YamlMime:PowerShellCmdlet1
uid: Az.Network.Set-AzLoadBalancerInboundNatRuleConfig
name: Set-AzLoadBalancerInboundNatRuleConfig
module: Az.Network
isPreview: false
summary: |-
  Sets an inbound NAT rule configuration for a load balancer.
description: |-
  The **Set-AzLoadBalancerInboundNatRuleConfig** cmdlet sets an inbound network address translation (NAT) rule configuration for an Azure load balancer.
parameters:
  cmdletParameters:
  - name: BackendPort
    type: <xref href="Int32" data-throw-if-not-resolved="False" />
    description: |-
      Specifies the backend port for traffic that is matched by this rule configuration.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: DefaultProfile
    type: <xref href="IAzureContextContainer" data-throw-if-not-resolved="False" />
    description: |-
      The credentials, account, tenant, and subscription used for communication with azure.
    aliases:
    - AzureRmContext
    - AzureCredential
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: EnableFloatingIP
    type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
    description: |-
      Indicates that this cmdlet enables a floating IP address for a rule configuration.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: FrontendIpConfiguration
    type: <xref href="PSFrontendIPConfiguration" data-throw-if-not-resolved="False" />
    description: |-
      Specifies a list of front-end IP addresses to associate with an inbound NAT rule configuration.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: SetByResource
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: FrontendIpConfigurationId
    type: <xref href="String" data-throw-if-not-resolved="False" />
    description: |-
      Specifies the ID for a front-end IP address configuration.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: SetByResourceId
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: FrontendPort
    type: <xref href="Int32" data-throw-if-not-resolved="False" />
    description: |-
      Specifies the front-end port that is matched by a load balancer rule configuration.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: IdleTimeoutInMinutes
    type: <xref href="Int32" data-throw-if-not-resolved="False" />
    description: |-
      Specifies the length of time, in minutes, that the state of conversations is maintained in a load balancer.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: LoadBalancer
    type: <xref href="PSLoadBalancer" data-throw-if-not-resolved="False" />
    description: |-
      Specifies a load balancer.
      This cmdlet sets an inbound NAT rule configuration for the load balancer that this parameter specifies.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: true
      valueFromPipeline: true
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: Name
    type: <xref href="String" data-throw-if-not-resolved="False" />
    description: |-
      Specifies the name of an inbound NAT rule configuration.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: Protocol
    type: <xref href="String" data-throw-if-not-resolved="False" />
    description: |-
      Specifies the protocol that is matched by an inbound NAT rule configuration.
      The acceptable values for this parameter are: Tcp or Udp.
    acceptedValues:
    - Tcp
    - Udp
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  commonParameters: |-
    This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable,
    -InformationAction, -InformationVariable, -OutBuffer, -OutVariable, -PipelineVariable,
    -ProgressAction, -Verbose, -WarningAction, and -WarningVariable. For more information, see
    [about_CommonParameters](https://go.microsoft.com/fwlink/?LinkID=113216).
syntaxes:
- syntax: |-
    ```Syntax
    Set-AzLoadBalancerInboundNatRuleConfig
        -Name <String>
        -LoadBalancer <PSLoadBalancer>
        [-FrontendIpConfigurationId <String>]
        [-Protocol <String>]
        [-FrontendPort <Int32>]
        [-BackendPort <Int32>]
        [-IdleTimeoutInMinutes <Int32>]
        [-EnableFloatingIP]
        [-DefaultProfile <IAzureContextContainer>]
        [<CommonParameters>]
    ```
  parameterSetName: SetByResourceId
  isDefault: false
- syntax: |-
    ```Syntax
    Set-AzLoadBalancerInboundNatRuleConfig
        -Name <String>
        -LoadBalancer <PSLoadBalancer>
        [-FrontendIpConfiguration <PSFrontendIPConfiguration>]
        [-Protocol <String>]
        [-FrontendPort <Int32>]
        [-BackendPort <Int32>]
        [-IdleTimeoutInMinutes <Int32>]
        [-EnableFloatingIP]
        [-DefaultProfile <IAzureContextContainer>]
        [<CommonParameters>]
    ```
  parameterSetName: SetByResource
  isDefault: false
inputs:
- name: <xref href="PSLoadBalancer" data-throw-if-not-resolved="False" />
  description: |-
    Parameter 'LoadBalancer' accepts value of type 'PSLoadBalancer' from the pipeline
outputs:
- name: <xref href="Microsoft.Azure.Commands.Network.Models.PSLoadBalancer" data-throw-if-not-resolved="False" />
examples:
- title: 'Example 1: Modify the inbound NAT rule configuration on a load balancer'
  description: |-
    ```
    PS C:\>$slb = Get-AzLoadBalancer -Name "MyLoadBalancer" -ResourceGroupName "MyResourceGroup"
    PS C:\> $slb | Add-AzLoadBalancerInboundNatRuleConfig -Name "NewNatRule" -FrontendIPConfiguration $slb.FrontendIpConfigurations[0] -Protocol "Tcp" -FrontendPort 3350 -BackendPort 3350 -EnableFloatingIP
    PS C:\> $slb | Set-AzLoadBalancerInboundNatRuleConfig -Name "NewNatRule" -FrontendIPConfiguration $slb.FrontendIpConfigurations[0] -Protocol "Tcp" -FrontendPort 3350 -BackendPort 3350
    ```

    The first command gets the load balancer named MyLoadBalancer, and then stores it in the $slb variable.

    The second command uses the pipeline operator to pass the load balancer in $slb to Add-AzLoadBalancerInboundNatRuleConfig, which adds an inbound NAT rule configuration to it.

    The third command passes the load balancer to **Set-AzLoadBalancerInboundNatRuleConfig**, which saves and updates the inbound NAT rule configuration.
    Note that the rule configuration was set without enabling floating IP, which had been enabled by the previous command.
links:
- text: Add-AzLoadBalancerInboundNatRuleConfig
  href: ./Add-AzLoadBalancerInboundNatRuleConfig.yml
- text: Get-AzLoadBalancer
  href: ./Get-AzLoadBalancer.yml
- text: Get-AzLoadBalancerInboundNatRuleConfig
  href: ./Get-AzLoadBalancerInboundNatRuleConfig.yml
- text: New-AzLoadBalancerInboundNatRuleConfig
  href: ./New-AzLoadBalancerInboundNatRuleConfig.yml
- text: Remove-AzLoadBalancerInboundNatRuleConfig
  href: ./Remove-AzLoadBalancerInboundNatRuleConfig.yml
metadata:
  content_git_url: https://github.com/Azure/azure-powershell/blob/Azs-tzl/src/Network/Network/help/Set-AzLoadBalancerInboundNatRuleConfig.md
  document type: cmdlet
  external help file: Microsoft.Azure.PowerShell.Cmdlets.Network.dll-Help.xml
  HelpUri: https://learn.microsoft.com/en-us/powershell/module/az.network/set-azloadbalancerinboundnatruleconfig
  Module Name: Az.Network
  ms.assetid: 87818605-EFA6-422E-9ECD-0A0BF269DCFD
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/Azs-tzl/src/Network/Network/help/Set-AzLoadBalancerInboundNatRuleConfig.md
  PlatyPS schema version: 2024-05-01
