### YamlMime:PowerShellCmdlet1
uid: Az.Resources.Get-AzManagedApplicationDefinition
name: Get-AzManagedApplicationDefinition
module: Az.Resources
isPreview: false
summary: |-
  Gets managed application definitions
description: |-
  The **Get-AzManagedApplicationDefinition** cmdlet gets managed application definitions
parameters:
  cmdletParameters:
  - name: ApiVersion
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      When set, indicates the version of the resource provider API to use.
      If not specified, the API version is automatically determined as the latest available.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: DefaultProfile
    type: <xref href="Microsoft.Azure.Commands.Common.Authentication.Abstractions.Core.IAzureContextContainer" data-throw-if-not-resolved="False" />
    description: |-
      The credentials, account, tenant, and subscription used for communication with azure.
    aliases:
    - AzContext
    - AzureRmContext
    - AzureCredential
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: Id
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      The fully qualified managed application definition Id, including the subscription.
      e.g.
      /subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}
    aliases:
    - ResourceId
    - ManagedApplicationDefinitionId
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: GetById
      position: Named
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: true
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: Name
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      The managed application definition name.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: GetByNameAndResourceGroup
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: true
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: Pre
    type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
    description: |-
      When set, indicates that the cmdlet should use pre-release API versions when automatically determining which version to use.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: ResourceGroupName
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      The resource group name.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: GetByNameAndResourceGroup
      position: Named
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: true
      valueFromRemainingArguments: false
    supportsWildcards: false
  commonParameters: |-
    This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable,
    -InformationAction, -InformationVariable, -OutBuffer, -OutVariable, -PipelineVariable,
    -ProgressAction, -Verbose, -WarningAction, and -WarningVariable. For more information, see
    [about_CommonParameters](https://go.microsoft.com/fwlink/?LinkID=113216).
syntaxes:
- syntax: |-
    ```Syntax
    Get-AzManagedApplicationDefinition
        -ResourceGroupName <String>
        [-Name <String>]
        [-ApiVersion <String>]
        [-Pre]
        [-DefaultProfile <IAzureContextContainer>]
        [<CommonParameters>]
    ```
  parameterSetName: GetByNameAndResourceGroup
  isDefault: true
- syntax: |-
    ```Syntax
    Get-AzManagedApplicationDefinition
        -Id <String>
        [-ApiVersion <String>]
        [-Pre]
        [-DefaultProfile <IAzureContextContainer>]
        [<CommonParameters>]
    ```
  parameterSetName: GetById
  isDefault: false
inputs:
- name: <xref href="System.String" data-throw-if-not-resolved="False" />
outputs:
- name: <xref href="System.Management.Automation.PSObject" data-throw-if-not-resolved="False" />
examples:
- title: 'Example 1: Get all managed application definitions under a resource group'
  description: |-
    ```powershell
    Get-AzManagedApplicationDefinition -ResourceGroupName "MyRG"
    ```

    This command gets the managed application definitions under resource group "MyRG"
- title: 'Example 2: Get a managed application definition'
  description: |-
    ```powershell
    Get-AzManagedApplicationDefinition -ResourceGroupName "MyRG" -Name "myManagedAppDef"
    ```

    This command gets the managed application definition "myManagedAppDef" under resource group "MyRG"
metadata:
  content_git_url: https://github.com/Azure/azure-powershell/blob/main/src/Resources/Resources/help/Get-AzManagedApplicationDefinition.md
  document type: cmdlet
  external help file: Microsoft.Azure.PowerShell.Cmdlets.ResourceManager.dll-Help.xml
  HelpUri: https://learn.microsoft.com/powershell/module/az.resources/get-azmanagedapplicationdefinition
  Module Name: Az.Resources
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/main/src/Resources/Resources/help/Get-AzManagedApplicationDefinition.md
  PlatyPS schema version: 2024-05-01
