### YamlMime:PowerShellCmdlet1
uid: Az.Network.New-AzNetworkManagerSecurityUserConfiguration
name: New-AzNetworkManagerSecurityUserConfiguration
module: Az.Network
isPreview: false
summary: |-
  Creates a security user configuration.
description: |-
  The **New-AzNetworkManagerSecurityUserConfiguration** cmdlet creates a security user configuration.
parameters:
  cmdletParameters:
  - name: AsJob
    type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
    description: |-
      Run cmdlet in the background
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: Confirm
    type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
    description: |-
      Prompts you for confirmation before running the cmdlet.
    aliases:
    - cf
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: DefaultProfile
    type: <xref href="Microsoft.Azure.Commands.Common.Authentication.Abstractions.Core.IAzureContextContainer" data-throw-if-not-resolved="False" />
    description: |-
      The credentials, account, tenant, and subscription used for communication with Azure.
    aliases:
    - AzContext
    - AzureRmContext
    - AzureCredential
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: Description
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      Description.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: true
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: Force
    type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
    description: |-
      Do not ask for confirmation if you want to overwrite a resource
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: Name
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      The resource name.
    aliases:
    - ResourceName
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: true
      valueFromRemainingArguments: false
    supportsWildcards: true
  - name: NetworkManagerName
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      The network manager name.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: true
      valueFromRemainingArguments: false
    supportsWildcards: true
  - name: ResourceGroupName
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      The resource group name.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: true
      valueFromRemainingArguments: false
    supportsWildcards: true
  - name: WhatIf
    type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
    description: |-
      Shows what would happen if the cmdlet runs.
      The cmdlet is not run.
    aliases:
    - wi
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  commonParameters: |-
    This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable,
    -InformationAction, -InformationVariable, -OutBuffer, -OutVariable, -PipelineVariable,
    -ProgressAction, -Verbose, -WarningAction, and -WarningVariable. For more information, see
    [about_CommonParameters](https://go.microsoft.com/fwlink/?LinkID=113216).
syntaxes:
- syntax: |-
    ```Syntax
    New-AzNetworkManagerSecurityUserConfiguration
        -Name <String>
        -NetworkManagerName <String>
        -ResourceGroupName <String>
        [-Description <String>]
        [-Force]
        [-AsJob]
        [-DefaultProfile <IAzureContextContainer>]
        [-WhatIf]
        [-Confirm]
        [<CommonParameters>]
    ```
  parameterSetName: Default
  isDefault: true
inputs:
- name: <xref href="System.String" data-throw-if-not-resolved="False" />
- name: <xref href="System.String" data-throw-if-not-resolved="False" />
- name: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
outputs:
- name: <xref href="Microsoft.Azure.Commands.Network.Models.NetworkManager.PSNetworkManagerSecurityUserConfiguration" data-throw-if-not-resolved="False" />
examples:
- title: Example 1
  description: |-
    ```powershell
    New-AzNetworkManagerSecurityUserConfiguration -ResourceGroupName "psResourceGroup" -NetworkManagerName "psNetworkManager" -Name "psSecurityUserConfig" -Description "TestDescription"
    ```

    ```output
    DisplayName                                 :
    Description                                 : TestDescription
    Type                                        : Microsoft.Network/networkManagers/securityUserConfigurations
    ProvisioningState                           : Succeeded
    SystemData                                  : Microsoft.Azure.Commands.Network.Models.NetworkManager.PSSystemData
    SystemDataText                              : {
                                                    "CreatedBy": "jaredgorthy@microsoft.com",
                                                    "CreatedByType": "User",
                                                    "CreatedAt": "2022-08-07T23:58:54.8549506Z",
                                                    "LastModifiedBy": "jaredgorthy@microsoft.com",
                                                    "LastModifiedByType": "User",
                                                    "LastModifiedAt": "2022-08-07T23:59:12.5789979Z"
                                                  }
    Name                                        : psSecurityUserConfig
    Etag                                        :
    Id                                          : /subscriptions/f0dc2b34-dfad-40e4-83e0-2309fed8d00b/resourceGroups/psResourceGroup/providers/Microsoft.Network/networkManagers/psNetworkManager/securityUserConfigurations/psSecurityUserConfig
    ```

    Creates a security user configuration.
links:
- text: Get-AzNetworkManagerSecurityUserConfiguration
  href: ./Get-AzNetworkManagerSecurityUserConfiguration.yml
- text: Remove-AzNetworkManagerSecurityUserConfiguration
  href: ./Remove-AzNetworkManagerSecurityUserConfiguration.yml
- text: Set-AzNetworkManagerSecurityUserConfiguration
  href: ./Set-AzNetworkManagerSecurityUserConfiguration.yml
metadata:
  content_git_url: https://github.com/Azure/azure-powershell/blob/main/src/Network/Network/help/New-AzNetworkManagerSecurityUserConfiguration.md
  document type: cmdlet
  external help file: Microsoft.Azure.PowerShell.Cmdlets.Network.dll-Help.xml
  HelpUri: https://learn.microsoft.com/powershell/module/az.network/new-aznetworkmanagersecurityuserconfiguration
  Module Name: Az.Network
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/main/src/Network/Network/help/New-AzNetworkManagerSecurityUserConfiguration.md
  PlatyPS schema version: 2024-05-01
