### YamlMime:PowerShellCmdlet1
uid: Az.Network.New-AzApplicationGatewayAutoscaleConfiguration
name: New-AzApplicationGatewayAutoscaleConfiguration
module: Az.Network
isPreview: false
summary: |-
  Creates a Autoscale Configuration for the Application Gateway.
description: |-
  The **New-AzApplicationGatewayAutoscaleConfiguration** cmdlet creates Autoscale Configuration for an Azure application gateway.
parameters:
  cmdletParameters:
  - name: Confirm
    type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
    description: |-
      Prompts you for confirmation before running the cmdlet.
    aliases:
    - cf
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: DefaultProfile
    type: <xref href="Microsoft.Azure.Commands.Common.Authentication.Abstractions.Core.IAzureContextContainer" data-throw-if-not-resolved="False" />
    description: |-
      The credentials, account, tenant, and subscription used for communication with Azure.
    aliases:
    - AzContext
    - AzureRmContext
    - AzureCredential
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: MaxCapacity
    type: <xref href="System.Nullable`1" data-throw-if-not-resolved="False" /><span>[</span><xref href="System.Int32" data-throw-if-not-resolved="False" /><span>]</span>
    description: |-
      Maximum capacity units that will always be available [and charged] for application gateway.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: MinCapacity
    type: <xref href="System.Int32" data-throw-if-not-resolved="False" />
    description: |-
      Minimum capacity units that will always be available [and charged] for application gateway.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: WhatIf
    type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
    description: |-
      Shows what would happen if the cmdlet runs.
      The cmdlet is not run.
    aliases:
    - wi
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  commonParameters: |-
    This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable,
    -InformationAction, -InformationVariable, -OutBuffer, -OutVariable, -PipelineVariable,
    -ProgressAction, -Verbose, -WarningAction, and -WarningVariable. For more information, see
    [about_CommonParameters](https://go.microsoft.com/fwlink/?LinkID=113216).
syntaxes:
- syntax: |-
    ```Syntax
    New-AzApplicationGatewayAutoscaleConfiguration
        -MinCapacity <Int32>
        [-MaxCapacity <Int32>]
        [-DefaultProfile <IAzureContextContainer>]
        [-WhatIf]
        [-Confirm]
        [<CommonParameters>]
    ```
  parameterSetName: Default
  isDefault: true
inputs:
- name: <xref href="None" data-throw-if-not-resolved="False" />
outputs:
- name: <xref href="Microsoft.Azure.Commands.Network.Models.PSApplicationGatewayAutoscaleConfiguration" data-throw-if-not-resolved="False" />
examples:
- title: Example 1
  description: |-
    ```powershell
    $AutoscaleConfig = New-AzApplicationGatewayAutoscaleConfiguration -MinCapacity 3
    $Gateway = New-AzApplicationGateway -Name "AppGateway01" -ResourceGroupName "ResourceGroup01" -Location "West US" -BackendAddressPools $Pool -BackendHttpSettingsCollection $PoolSetting -FrontendIpConfigurations $FrontEndIpConfig -GatewayIpConfigurations $GatewayIpConfig -FrontendPorts $FrontEndPort -HttpListeners $Listener -RequestRoutingRules $Rule -Sku $Sku -AutoscaleConfiguration $AutoscaleConfig
    ```

    The first command creates an autoscale configuration with minimum capacity 3.
    The second command creates an application gateway with the autoscale configuration.
- title: Example 2
  description: |-
    ```powershell
    $gw = Get-AzApplicationGateway -Name "ApplicationGateway01" -ResourceGroupName "ResourceGroup01"
    $gw.Sku.Capacity = $null
    $gw.AutoscaleConfiguration = New-AzApplicationGatewayAutoscaleConfiguration -MinCapacity 2 -MaxCapacity 4
    $gw = Set-AzApplicationGateway -ApplicationGateway $gw
    ```

    The first command gets the configuration of the Application Gateway into a variable.
    The second command clears the SKU Capacity variable to allow the Autoscale Configuration to be set.
    The third command specifies a new AutoScale Configuration for the Application Gateway.
    The fourth command applies the new configuration to the Application Gateway.
links:
- text: Get-AzApplicationGatewayAutoscaleConfiguration
  href: ./Get-AzApplicationGatewayAutoscaleConfiguration.yml
- text: Remove-AzApplicationGatewayAutoscaleConfiguration
  href: ./Remove-AzApplicationGatewayAutoscaleConfiguration.yml
- text: Set-AzApplicationGatewayAutoscaleConfiguration
  href: ./Set-AzApplicationGatewayAutoscaleConfiguration.yml
metadata:
  content_git_url: https://github.com/Azure/azure-powershell/blob/main/src/Network/Network/help/New-AzApplicationGatewayAutoscaleConfiguration.md
  document type: cmdlet
  external help file: Microsoft.Azure.PowerShell.Cmdlets.Network.dll-Help.xml
  HelpUri: https://learn.microsoft.com/powershell/module/az.network/new-azapplicationgatewayautoscaleconfiguration
  Module Name: Az.Network
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/main/src/Network/Network/help/New-AzApplicationGatewayAutoscaleConfiguration.md
  PlatyPS schema version: 2024-05-01
