### YamlMime:PowerShellCmdlet1
uid: Az.Network.New-AzNetworkWatcherConnectionMonitorProtocolConfigurationObject
name: New-AzNetworkWatcherConnectionMonitorProtocolConfigurationObject
module: Az.Network
isPreview: false
summary: |-
  Create protocol configuration used to perform test evaluation over TCP, HTTP or ICMP.
description: |-
  The New-AzNetworkWatcherConnectionMonitorProtocolConfigurationObject cmdlet creates protocol configuration used to perform test evaluation over TCP, HTTP or ICMP.
parameters:
  cmdletParameters:
  - name: DefaultProfile
    type: <xref href="Microsoft.Azure.Commands.Common.Authentication.Abstractions.Core.IAzureContextContainer" data-throw-if-not-resolved="False" />
    description: |-
      The credentials, account, tenant, and subscription used for communication with Azure.
    aliases:
    - AzContext
    - AzureRmContext
    - AzureCredential
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: DestinationPortBehavior
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      Destination port behavior.
      Supported values are None, ListenIfAvailable.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: TCP
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: DisableTraceRoute
    type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
    description: |-
      Value indicating whether path evaluation with trace route should be disabled.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: TCP
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    - name: ICMP
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: HttpProtocol
    type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
    description: |-
      HTTP protocol switch.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: HTTP
      position: Named
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: IcmpProtocol
    type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
    description: |-
      ICMP protocol switch.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: ICMP
      position: Named
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: Method
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      The HTTP method to use.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: HTTP
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: Path
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      The path component of the URI.
      For instance, "/dir1/dir2".
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: HTTP
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: Port
    type: <xref href="System.Nullable`1" data-throw-if-not-resolved="False" /><span>[</span><xref href="System.UInt16" data-throw-if-not-resolved="False" /><span>]</span>
    description: |-
      The port to connect to.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: TCP
      position: Named
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: PreferHTTPS
    type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
    description: |-
      Value indicating whether HTTPS is preferred over HTTP in cases where the choice is not explicit.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: HTTP
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: RequestHeader
    type: <xref href="System.Collections.Hashtable" data-throw-if-not-resolved="False" />
    description: |-
      The HTTP headers to transmit with the request.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: HTTP
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: TcpProtocol
    type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
    description: |-
      TCP protocol switch.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: TCP
      position: Named
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: ValidStatusCodeRange
    type: <xref href="System.String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
    description: |-
      HTTP status codes to consider successful.
      For instance, "2xx,301-304,418".
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: HTTP
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  commonParameters: |-
    This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable,
    -InformationAction, -InformationVariable, -OutBuffer, -OutVariable, -PipelineVariable,
    -ProgressAction, -Verbose, -WarningAction, and -WarningVariable. For more information, see
    [about_CommonParameters](https://go.microsoft.com/fwlink/?LinkID=113216).
syntaxes:
- syntax: |-
    ```Syntax
    New-AzNetworkWatcherConnectionMonitorProtocolConfigurationObject
        -Port <UInt16>
        [-TcpProtocol]
        [-DisableTraceRoute]
        [-DestinationPortBehavior <String>]
        [-DefaultProfile <IAzureContextContainer>]
        [<CommonParameters>]
    ```
  parameterSetName: TCP
  isDefault: false
- syntax: |-
    ```Syntax
    New-AzNetworkWatcherConnectionMonitorProtocolConfigurationObject
        [-HttpProtocol]
        [-Port <UInt16>]
        [-Method <String>]
        [-Path <String>]
        [-RequestHeader <Hashtable>]
        [-ValidStatusCodeRange <String[]>]
        [-PreferHTTPS]
        [-DefaultProfile <IAzureContextContainer>]
        [<CommonParameters>]
    ```
  parameterSetName: HTTP
  isDefault: false
- syntax: |-
    ```Syntax
    New-AzNetworkWatcherConnectionMonitorProtocolConfigurationObject
        [-IcmpProtocol]
        [-DisableTraceRoute]
        [-DefaultProfile <IAzureContextContainer>]
        [<CommonParameters>]
    ```
  parameterSetName: ICMP
  isDefault: false
inputs:
- name: <xref href="None" data-throw-if-not-resolved="False" />
outputs:
- name: <xref href="Microsoft.Azure.Commands.Network.Models.PSNetworkWatcherConnectionMonitorTcpConfiguration" data-throw-if-not-resolved="False" />
- name: <xref href="Microsoft.Azure.Commands.Network.Models.PSNetworkWatcherConnectionMonitorHttpConfiguration" data-throw-if-not-resolved="False" />
- name: <xref href="Microsoft.Azure.Commands.Network.Models.PSNetworkWatcherConnectionMonitorIcmpConfiguration" data-throw-if-not-resolved="False" />
examples:
- title: Example 1
  description: |-
    ```powershell
    $TcpProtocolConfiguration = New-AzNetworkWatcherConnectionMonitorProtocolConfigurationObject -TcpProtocol -Port 80 -DisableTraceRoute
    ```

    ```output
    Port              : 80
    DisableTraceRoute : False
    ```
- title: Example 2
  description: |-
    Create protocol configuration used to perform test evaluation over TCP, HTTP or ICMP. (autogenerated)

    <!-- Aladdin Generated Example -->


    ```powershell
    New-AzNetworkWatcherConnectionMonitorProtocolConfigurationObject -IcmpProtocol
    ```
metadata:
  content_git_url: https://github.com/Azure/azure-powershell/blob/main/src/Network/Network/help/New-AzNetworkWatcherConnectionMonitorProtocolConfigurationObject.md
  document type: cmdlet
  external help file: Microsoft.Azure.PowerShell.Cmdlets.Network.dll-Help.xml
  HelpUri: https://learn.microsoft.com/powershell/module/az.network/new-aznetworkwatcherconnectionmonitorprotocolconfigurationobject
  Module Name: Az.Network
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/main/src/Network/Network/help/New-AzNetworkWatcherConnectionMonitorProtocolConfigurationObject.md
  PlatyPS schema version: 2024-05-01
