### YamlMime:PowerShellCmdlet1
uid: Az.Aks.Get-AzAksMaintenanceConfiguration
name: Get-AzAksMaintenanceConfiguration
module: Az.Aks
isPreview: false
summary: |-
  Gets the specified maintenance configuration of a managed cluster.
description: |-
  Gets the specified maintenance configuration of a managed cluster.
parameters:
  cmdletParameters:
  - name: ConfigName
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      The name of the maintenance configuration.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: Get
      position: Named
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: DefaultProfile
    type: <xref href="System.Management.Automation.PSObject" data-throw-if-not-resolved="False" />
    description: |-
      The DefaultProfile parameter is not functional.
      Use the SubscriptionId parameter when available if executing the cmdlet against a different subscription.
    aliases:
    - AzureRMContext
    - AzureCredential
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: InputObject
    type: <xref href="Microsoft.Azure.PowerShell.Cmdlets.Aks.Models.IAksIdentity" data-throw-if-not-resolved="False" />
    description: |-
      Identity Parameter
      To construct, see NOTES section for INPUTOBJECT properties and create a hash table.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: GetViaIdentity
      position: Named
      isRequired: true
      valueFromPipeline: true
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: ResourceGroupName
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      The name of the resource group.
      The name is case insensitive.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: List
      position: Named
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    - name: Get
      position: Named
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: ResourceName
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      The name of the managed cluster resource.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: List
      position: Named
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    - name: Get
      position: Named
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: SubscriptionId
    type: <xref href="System.String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
    description: |-
      The ID of the target subscription.
    defaultValue: (Get-AzContext).Subscription.Id
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: List
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    - name: Get
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  commonParameters: |-
    This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable,
    -InformationAction, -InformationVariable, -OutBuffer, -OutVariable, -PipelineVariable,
    -ProgressAction, -Verbose, -WarningAction, and -WarningVariable. For more information, see
    [about_CommonParameters](https://go.microsoft.com/fwlink/?LinkID=113216).
syntaxes:
- syntax: |-
    ```Syntax
    Get-AzAksMaintenanceConfiguration
        -ResourceGroupName <String>
        -ResourceName <String>
        [-SubscriptionId <String[]>]
        [-DefaultProfile <PSObject>]
        [<CommonParameters>]
    ```
  parameterSetName: List
  isDefault: true
- syntax: |-
    ```Syntax
    Get-AzAksMaintenanceConfiguration
        -ConfigName <String>
        -ResourceGroupName <String>
        -ResourceName <String>
        [-SubscriptionId <String[]>]
        [-DefaultProfile <PSObject>]
        [<CommonParameters>]
    ```
  parameterSetName: Get
  isDefault: false
- syntax: |-
    ```Syntax
    Get-AzAksMaintenanceConfiguration
        -InputObject <IAksIdentity>
        [-DefaultProfile <PSObject>]
        [<CommonParameters>]
    ```
  parameterSetName: GetViaIdentity
  isDefault: false
inputs:
- name: <xref href="Microsoft.Azure.PowerShell.Cmdlets.Aks.Models.IAksIdentity" data-throw-if-not-resolved="False" />
outputs:
- name: <xref href="Microsoft.Azure.PowerShell.Cmdlets.Aks.Models.Api20230201.IMaintenanceConfiguration" data-throw-if-not-resolved="False" />
examples:
- title: 'Example 1: List all maintenance configurations for a managed cluster'
  description: |-
    ```powershell
    Get-AzAksMaintenanceConfiguration -ResourceGroupName mygroup -ResourceName myCluster
    ```

    ```output
    Name
    ----
    aks_maintenance_config1
    aks_maintenance_config2
    ```

    List all maintenance configurations for a managed cluster "myCluster".
- title: 'Example 2: Get a maintenance configuration with its config name'
  description: |-
    ```powershell
    Get-AzAksMaintenanceConfiguration -ResourceGroupName mygroup -ResourceName myCluster -ConfigName 'aks_maintenance_config'
    ```

    ```output
    Name
    ----
    aks_maintenance_config1
    ```

    Get a maintenance configuration with name "aks_maintenance_config" for a managed cluster "myCluster".
- title: 'Example 3: Get a maintenance configuration via identity'
  description: |-
    ```powershell
    $TimeSpan = New-AzAksTimeSpanObject -Start (Get-Date -Year 2023 -Month 3 -Day 1) -End (Get-Date -Year 2023 -Month 3 -Day 2)
    $TimeInWeek = New-AzAksTimeInWeekObject -Day 'Sunday' -HourSlot 1,2
    $MaintenanceConfig = New-AzAksMaintenanceConfiguration -ResourceGroupName mygroup -ResourceName myCluster -ConfigName 'aks_maintenance_config' -TimeInWeek $TimeInWeek -NotAllowedTime $TimeSpan
    $MaintenanceConfig | Get-AzAksMaintenanceConfiguration
    ```

    ```output
    Name
    ----
    aks_maintenance_config
    ```

    Get a maintenance configuration via identity for a managed cluster "myCluster".
metadata:
  content_git_url: https://github.com/Azure/azure-powershell/blob/main/src/Aks/Aks/help/Get-AzAksMaintenanceConfiguration.md
  document type: cmdlet
  external help file: Az.Aks-help.xml
  HelpUri: https://learn.microsoft.com/powershell/module/az.aks/get-azaksmaintenanceconfiguration
  Module Name: Az.Aks
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/main/src/Aks/Aks/help/Get-AzAksMaintenanceConfiguration.md
  PlatyPS schema version: 2024-05-01
